-- GENERATED by `python -m cloud.intel.store.ddl --write` from cloud/intel/store/spec.py.
-- Do not edit by hand: change the specs and regenerate before this migration is
-- applied anywhere; after that, write a new migration.
--
-- AI Control Room: agent sessions, messages, runs, tool-call steps, approvals,
-- results, workspace AI memory, proactive insights and saved requests/views.
-- Same tenancy and RLS model as 0003 (workspace membership via member_role()).

-- ---------------------------------------------------------------------------
-- A Control Room conversation: messages plus the current working result set.
create table careercloud.agent_sessions (
  id                     text primary key check (id ~ '^as_[0-9a-f]{32}$'),
  workspace_id           uuid not null references careercloud.workspaces (id) on delete cascade,
  created_at             timestamptz not null default now(),
  updated_at             timestamptz not null default now(),
  created_by             uuid,
  version                integer not null default 1,
  title                  text not null check (char_length(title) <= 300),
  mode                   text not null default 'auto' check (mode in ('auto', 'research', 'prospecting', 'hiring', 'data', 'campaign', 'crm', 'monitoring')),
  status                 text not null default 'active' check (status in ('active', 'archived')),
  working_set            jsonb not null default '{}'::jsonb,
  last_run_id            text check (char_length(last_run_id) <= 40)
);

create index agent_sessions_by_ws_created on careercloud.agent_sessions (workspace_id, created_at desc, id desc);
create index agent_sessions_by_ws_mode on careercloud.agent_sessions (workspace_id, mode);
create index agent_sessions_by_ws_status on careercloud.agent_sessions (workspace_id, status);
create trigger agent_sessions_guard before update on careercloud.agent_sessions
  for each row execute function careercloud.guard_platform_row();
alter table careercloud.agent_sessions enable row level security;
create policy agent_sessions_select on careercloud.agent_sessions for select to authenticated
  using (careercloud.is_member(workspace_id));
create policy agent_sessions_insert on careercloud.agent_sessions for insert to authenticated
  with check (careercloud.can_write(workspace_id) and created_by = auth.uid());
create policy agent_sessions_update on careercloud.agent_sessions for update to authenticated
  using (careercloud.can_write(workspace_id)) with check (careercloud.can_write(workspace_id));
create policy agent_sessions_delete on careercloud.agent_sessions for delete to authenticated
  using (careercloud.can_write(workspace_id));
grant select, insert, update, delete on careercloud.agent_sessions to authenticated;

-- ---------------------------------------------------------------------------
-- agent_messages
create table careercloud.agent_messages (
  id                     text primary key check (id ~ '^am_[0-9a-f]{32}$'),
  workspace_id           uuid not null references careercloud.workspaces (id) on delete cascade,
  created_at             timestamptz not null default now(),
  updated_at             timestamptz not null default now(),
  created_by             uuid,
  version                integer not null default 1,
  session_id             text not null check (char_length(session_id) <= 40),
  role                   text not null default 'user' check (role in ('user', 'assistant', 'system')),
  content                text not null check (char_length(content) <= 20000),
  run_id                 text check (char_length(run_id) <= 40),
  data                   jsonb not null default '{}'::jsonb
);

create index agent_messages_by_ws_created on careercloud.agent_messages (workspace_id, created_at desc, id desc);
create index agent_messages_by_ws_session_id on careercloud.agent_messages (workspace_id, session_id);
create index agent_messages_by_ws_role on careercloud.agent_messages (workspace_id, role);
create trigger agent_messages_guard before update on careercloud.agent_messages
  for each row execute function careercloud.guard_platform_row();
alter table careercloud.agent_messages enable row level security;
create policy agent_messages_select on careercloud.agent_messages for select to authenticated
  using (careercloud.is_member(workspace_id));
create policy agent_messages_insert on careercloud.agent_messages for insert to authenticated
  with check (careercloud.can_write(workspace_id) and created_by = auth.uid());
grant select, insert on careercloud.agent_messages to authenticated;

-- ---------------------------------------------------------------------------
-- One request: intent, plan, estimate, execution state and synthesised result.
create table careercloud.agent_runs (
  id                     text primary key check (id ~ '^ar_[0-9a-f]{32}$'),
  workspace_id           uuid not null references careercloud.workspaces (id) on delete cascade,
  created_at             timestamptz not null default now(),
  updated_at             timestamptz not null default now(),
  created_by             uuid,
  version                integer not null default 1,
  session_id             text check (char_length(session_id) <= 40),
  request                text not null check (char_length(request) <= 8000),
  mode                   text not null check (char_length(mode) <= 40),
  intent                 jsonb not null default '{}'::jsonb,
  plan                   jsonb not null default '[]'::jsonb,
  status                 text not null default 'planned' check (status in ('planned', 'running', 'awaiting_approval', 'completed', 'failed', 'cancelled')),
  planner                text check (char_length(planner) <= 60),
  estimate               jsonb not null default '{}'::jsonb,
  result                 jsonb not null default '{}'::jsonb,
  summary                text check (char_length(summary) <= 20000),
  task_id                text check (char_length(task_id) <= 40),
  error                  text check (char_length(error) <= 4000),
  progress               jsonb not null default '{}'::jsonb
);

create index agent_runs_by_ws_created on careercloud.agent_runs (workspace_id, created_at desc, id desc);
create index agent_runs_by_ws_session_id on careercloud.agent_runs (workspace_id, session_id);
create index agent_runs_by_ws_status on careercloud.agent_runs (workspace_id, status);
create trigger agent_runs_guard before update on careercloud.agent_runs
  for each row execute function careercloud.guard_platform_row();
alter table careercloud.agent_runs enable row level security;
create policy agent_runs_select on careercloud.agent_runs for select to authenticated
  using (careercloud.is_member(workspace_id));
create policy agent_runs_insert on careercloud.agent_runs for insert to authenticated
  with check (careercloud.can_write(workspace_id) and created_by = auth.uid());
create policy agent_runs_update on careercloud.agent_runs for update to authenticated
  using (careercloud.can_write(workspace_id)) with check (careercloud.can_write(workspace_id));
create policy agent_runs_delete on careercloud.agent_runs for delete to authenticated
  using (careercloud.can_write(workspace_id));
grant select, insert, update, delete on careercloud.agent_runs to authenticated;

-- ---------------------------------------------------------------------------
-- Every tool call: parameters (secrets redacted), risk, credits, output and errors.
create table careercloud.agent_steps (
  id                     text primary key check (id ~ '^sp_[0-9a-f]{32}$'),
  workspace_id           uuid not null references careercloud.workspaces (id) on delete cascade,
  created_at             timestamptz not null default now(),
  updated_at             timestamptz not null default now(),
  created_by             uuid,
  version                integer not null default 1,
  run_id                 text not null check (char_length(run_id) <= 40),
  position               integer not null check (position >= 0),
  tool                   text not null check (char_length(tool) <= 80),
  params                 jsonb not null default '{}'::jsonb,
  risk                   text not null check (char_length(risk) <= 20),
  status                 text not null default 'planned' check (status in ('planned', 'running', 'done', 'failed', 'skipped', 'awaiting_approval', 'rejected')),
  requires_approval      boolean not null default false,
  estimate               jsonb not null default '{}'::jsonb,
  output                 jsonb not null default '{}'::jsonb,
  error                  text check (char_length(error) <= 4000),
  started_at             timestamptz,
  finished_at            timestamptz,
  duration_ms            double precision,
  reservation_ids        text[] not null default '{}'::text[],
  idempotency_key        text check (char_length(idempotency_key) <= 200)
);

create index agent_steps_by_ws_created on careercloud.agent_steps (workspace_id, created_at desc, id desc);
create index agent_steps_by_ws_run_id on careercloud.agent_steps (workspace_id, run_id);
create index agent_steps_by_ws_tool on careercloud.agent_steps (workspace_id, tool);
create index agent_steps_by_ws_status on careercloud.agent_steps (workspace_id, status);
create unique index agent_steps_uq_run_id_position on careercloud.agent_steps (workspace_id, run_id, position);
create trigger agent_steps_guard before update on careercloud.agent_steps
  for each row execute function careercloud.guard_platform_row();
alter table careercloud.agent_steps enable row level security;
create policy agent_steps_select on careercloud.agent_steps for select to authenticated
  using (careercloud.is_member(workspace_id));
grant select on careercloud.agent_steps to authenticated;

-- ---------------------------------------------------------------------------
-- agent_approvals
create table careercloud.agent_approvals (
  id                     text primary key check (id ~ '^ap_[0-9a-f]{32}$'),
  workspace_id           uuid not null references careercloud.workspaces (id) on delete cascade,
  created_at             timestamptz not null default now(),
  updated_at             timestamptz not null default now(),
  created_by             uuid,
  version                integer not null default 1,
  run_id                 text not null check (char_length(run_id) <= 40),
  step_id                text not null check (char_length(step_id) <= 40),
  action                 text not null check (char_length(action) <= 300),
  reason                 text check (char_length(reason) <= 4000),
  risk                   text not null check (char_length(risk) <= 20),
  impact                 jsonb not null default '{}'::jsonb,
  credits                jsonb not null default '{}'::jsonb,
  status                 text not null default 'pending' check (status in ('pending', 'approved', 'rejected', 'expired')),
  decided_by             uuid,
  decided_at             timestamptz
);

create index agent_approvals_by_ws_created on careercloud.agent_approvals (workspace_id, created_at desc, id desc);
create index agent_approvals_by_ws_run_id on careercloud.agent_approvals (workspace_id, run_id);
create index agent_approvals_by_ws_step_id on careercloud.agent_approvals (workspace_id, step_id);
create index agent_approvals_by_ws_status on careercloud.agent_approvals (workspace_id, status);
create trigger agent_approvals_guard before update on careercloud.agent_approvals
  for each row execute function careercloud.guard_platform_row();
alter table careercloud.agent_approvals enable row level security;
create policy agent_approvals_select on careercloud.agent_approvals for select to authenticated
  using (careercloud.is_member(workspace_id));
grant select on careercloud.agent_approvals to authenticated;

-- ---------------------------------------------------------------------------
-- agent_results
create table careercloud.agent_results (
  id                     text primary key check (id ~ '^ax_[0-9a-f]{32}$'),
  workspace_id           uuid not null references careercloud.workspaces (id) on delete cascade,
  created_at             timestamptz not null default now(),
  updated_at             timestamptz not null default now(),
  created_by             uuid,
  version                integer not null default 1,
  run_id                 text not null check (char_length(run_id) <= 40),
  entity_type            text not null check (char_length(entity_type) <= 40),
  entity_id              text check (char_length(entity_id) <= 40),
  rank                   integer not null check (rank >= 0),
  title                  text check (char_length(title) <= 500),
  data                   jsonb not null default '{}'::jsonb,
  score                  double precision check (score >= 0 and score <= 100),
  reasons                jsonb not null default '[]'::jsonb,
  evidence               jsonb not null default '[]'::jsonb
);

create index agent_results_by_ws_created on careercloud.agent_results (workspace_id, created_at desc, id desc);
create index agent_results_by_ws_run_id on careercloud.agent_results (workspace_id, run_id);
create index agent_results_by_ws_entity_type on careercloud.agent_results (workspace_id, entity_type);
create trigger agent_results_guard before update on careercloud.agent_results
  for each row execute function careercloud.guard_platform_row();
alter table careercloud.agent_results enable row level security;
create policy agent_results_select on careercloud.agent_results for select to authenticated
  using (careercloud.is_member(workspace_id));
grant select on careercloud.agent_results to authenticated;

-- ---------------------------------------------------------------------------
-- Workspace AI memory. Never holds secrets.
create table careercloud.ai_memory (
  id                     text primary key check (id ~ '^mm_[0-9a-f]{32}$'),
  workspace_id           uuid not null references careercloud.workspaces (id) on delete cascade,
  created_at             timestamptz not null default now(),
  updated_at             timestamptz not null default now(),
  created_by             uuid,
  version                integer not null default 1,
  kind                   text not null default 'alias' check (kind in ('alias', 'preference', 'campaign_definition', 'saved_pattern', 'source_priority', 'scoring_preference', 'allowed_providers', 'default_filter', 'preferred_fields')),
  key                    text not null check (char_length(key) <= 120),
  value                  jsonb not null default '{}'::jsonb,
  text                   text check (char_length(text) <= 2000),
  enabled                boolean not null default true
);

create index ai_memory_by_ws_created on careercloud.ai_memory (workspace_id, created_at desc, id desc);
create index ai_memory_by_ws_kind on careercloud.ai_memory (workspace_id, kind);
create unique index ai_memory_uq_kind_key on careercloud.ai_memory (workspace_id, kind, key);
create trigger ai_memory_guard before update on careercloud.ai_memory
  for each row execute function careercloud.guard_platform_row();
alter table careercloud.ai_memory enable row level security;
create policy ai_memory_select on careercloud.ai_memory for select to authenticated
  using (careercloud.is_member(workspace_id));
create policy ai_memory_insert on careercloud.ai_memory for insert to authenticated
  with check (careercloud.can_write(workspace_id) and created_by = auth.uid());
create policy ai_memory_update on careercloud.ai_memory for update to authenticated
  using (careercloud.can_write(workspace_id)) with check (careercloud.can_write(workspace_id));
create policy ai_memory_delete on careercloud.ai_memory for delete to authenticated
  using (careercloud.can_write(workspace_id));
grant select, insert, update, delete on careercloud.ai_memory to authenticated;

-- ---------------------------------------------------------------------------
-- ai_insights
create table careercloud.ai_insights (
  id                     text primary key check (id ~ '^in_[0-9a-f]{32}$'),
  workspace_id           uuid not null references careercloud.workspaces (id) on delete cascade,
  created_at             timestamptz not null default now(),
  updated_at             timestamptz not null default now(),
  created_by             uuid,
  version                integer not null default 1,
  kind                   text not null check (char_length(kind) <= 60),
  title                  text not null check (char_length(title) <= 500),
  detail                 text check (char_length(detail) <= 4000),
  severity               text not null default 'info' check (severity in ('info', 'notable', 'high')),
  company_ids            text[] not null default '{}'::text[],
  evidence               jsonb not null default '[]'::jsonb,
  status                 text not null default 'new' check (status in ('new', 'seen', 'dismissed', 'acted')),
  fingerprint            text not null check (char_length(fingerprint) <= 200),
  suggested_request      text check (char_length(suggested_request) <= 2000)
);

create index ai_insights_by_ws_created on careercloud.ai_insights (workspace_id, created_at desc, id desc);
create index ai_insights_by_ws_kind on careercloud.ai_insights (workspace_id, kind);
create index ai_insights_by_ws_severity on careercloud.ai_insights (workspace_id, severity);
create index ai_insights_by_ws_status on careercloud.ai_insights (workspace_id, status);
create unique index ai_insights_uq_fingerprint on careercloud.ai_insights (workspace_id, fingerprint);
create trigger ai_insights_guard before update on careercloud.ai_insights
  for each row execute function careercloud.guard_platform_row();
alter table careercloud.ai_insights enable row level security;
create policy ai_insights_select on careercloud.ai_insights for select to authenticated
  using (careercloud.is_member(workspace_id));
create policy ai_insights_insert on careercloud.ai_insights for insert to authenticated
  with check (careercloud.can_write(workspace_id) and created_by = auth.uid());
create policy ai_insights_update on careercloud.ai_insights for update to authenticated
  using (careercloud.can_write(workspace_id)) with check (careercloud.can_write(workspace_id));
create policy ai_insights_delete on careercloud.ai_insights for delete to authenticated
  using (careercloud.can_write(workspace_id));
grant select, insert, update, delete on careercloud.ai_insights to authenticated;

-- ---------------------------------------------------------------------------
-- saved_requests
create table careercloud.saved_requests (
  id                     text primary key check (id ~ '^sv_[0-9a-f]{32}$'),
  workspace_id           uuid not null references careercloud.workspaces (id) on delete cascade,
  created_at             timestamptz not null default now(),
  updated_at             timestamptz not null default now(),
  created_by             uuid,
  version                integer not null default 1,
  name                   text not null check (char_length(name) <= 200),
  request                text not null check (char_length(request) <= 8000),
  mode                   text check (char_length(mode) <= 40),
  kind                   text not null default 'request' check (kind in ('request', 'view')),
  config                 jsonb not null default '{}'::jsonb
);

create index saved_requests_by_ws_created on careercloud.saved_requests (workspace_id, created_at desc, id desc);
create index saved_requests_by_ws_kind on careercloud.saved_requests (workspace_id, kind);
create trigger saved_requests_guard before update on careercloud.saved_requests
  for each row execute function careercloud.guard_platform_row();
alter table careercloud.saved_requests enable row level security;
create policy saved_requests_select on careercloud.saved_requests for select to authenticated
  using (careercloud.is_member(workspace_id));
create policy saved_requests_insert on careercloud.saved_requests for insert to authenticated
  with check (careercloud.can_write(workspace_id) and created_by = auth.uid());
create policy saved_requests_update on careercloud.saved_requests for update to authenticated
  using (careercloud.can_write(workspace_id)) with check (careercloud.can_write(workspace_id));
create policy saved_requests_delete on careercloud.saved_requests for delete to authenticated
  using (careercloud.can_write(workspace_id));
grant select, insert, update, delete on careercloud.saved_requests to authenticated;

-- ---------------------------------------------------------------------------
-- Supabase's anonymous role gets nothing in this schema.
-- ---------------------------------------------------------------------------

do $anon$
begin
  if exists (select 1 from pg_roles where rolname = 'anon') then
    revoke all on all tables in schema careercloud from anon;
    revoke all on all functions in schema careercloud from anon;
  end if;
end
$anon$;
