-- GENERATED by `python -m cloud.intel.store.ddl --write` from cloud/intel/store/spec.py.
-- Do not edit by hand: change the specs and regenerate before this migration is
-- applied anywhere; after that, write a new migration.
--
-- Real AI providers: per-call usage (provider, model, tokens, estimated cost,
-- request id) for budgets and cost reporting. Same tenancy and RLS model as 0003.

-- ---------------------------------------------------------------------------
-- One row per external AI call: provider, model, tokens, estimated cost and request id.
create table careercloud.ai_usage (
  id                     text primary key check (id ~ '^ai_[0-9a-f]{32}$'),
  workspace_id           uuid not null references careercloud.workspaces (id) on delete cascade,
  created_at             timestamptz not null default now(),
  updated_at             timestamptz not null default now(),
  created_by             uuid,
  version                integer not null default 1,
  provider               text not null check (char_length(provider) <= 60),
  model                  text not null check (char_length(model) <= 120),
  purpose                text not null check (char_length(purpose) <= 60),
  success                boolean not null default true,
  error                  text check (char_length(error) <= 1000),
  prompt_tokens          integer check (prompt_tokens >= 0),
  completion_tokens      integer check (completion_tokens >= 0),
  total_tokens           integer check (total_tokens >= 0),
  estimated_cost_usd     double precision check (estimated_cost_usd >= 0),
  request_id             text check (char_length(request_id) <= 200),
  latency_ms             double precision check (latency_ms >= 0),
  run_id                 text check (char_length(run_id) <= 40)
);

create index ai_usage_by_ws_created on careercloud.ai_usage (workspace_id, created_at desc, id desc);
create index ai_usage_by_ws_provider on careercloud.ai_usage (workspace_id, provider);
create index ai_usage_by_ws_purpose on careercloud.ai_usage (workspace_id, purpose);
create index ai_usage_by_ws_run_id on careercloud.ai_usage (workspace_id, run_id);
create trigger ai_usage_guard before update on careercloud.ai_usage
  for each row execute function careercloud.guard_platform_row();
alter table careercloud.ai_usage enable row level security;
create policy ai_usage_select on careercloud.ai_usage for select to authenticated
  using (careercloud.is_member(workspace_id));
grant select on careercloud.ai_usage to authenticated;

-- ---------------------------------------------------------------------------
-- Supabase's anonymous role gets nothing in this schema.
-- ---------------------------------------------------------------------------

do $anon$
begin
  if exists (select 1 from pg_roles where rolname = 'anon') then
    revoke all on all tables in schema careercloud from anon;
    revoke all on all functions in schema careercloud from anon;
  end if;
end
$anon$;
