-- GENERATED by `python -m cloud.intel.store.ddl --write` from cloud/intel/store/spec.py.
-- Do not edit by hand: change the specs and regenerate before this migration is
-- applied anywhere; after that, write a new migration.
--
-- AI scraper V2-V4: every page a run visited, saved templates, CRM proposals
-- (applied only after review), and the fine-grained scraper run states.
-- Same tenancy and RLS model as 0003.

-- ---------------------------------------------------------------------------
-- scrape_runs.status: widened choices
alter table careercloud.scrape_runs drop constraint scrape_runs_status_check,
  add constraint scrape_runs_status_check check (status in ('queued', 'planning', 'fetching', 'extracting', 'paginating', 'enriching', 'validating', 'normalizing', 'saving', 'completed', 'failed', 'cancelled', 'paused', 'running'));

-- ---------------------------------------------------------------------------
-- Every page a scraper run visited, with its outcome (never fetched twice in one run).
create table careercloud.scrape_pages (
  id                     text primary key check (id ~ '^spg_[0-9a-f]{32}$'),
  workspace_id           uuid not null references careercloud.workspaces (id) on delete cascade,
  created_at             timestamptz not null default now(),
  updated_at             timestamptz not null default now(),
  created_by             uuid,
  version                integer not null default 1,
  run_id                 text not null check (char_length(run_id) <= 40),
  input_index            integer not null default 0 check (input_index >= 0),
  url_key                text not null check (char_length(url_key) <= 64),
  url                    text not null check (char_length(url) <= 2048),
  final_url              text check (char_length(final_url) <= 2048),
  kind                   text not null default 'input' check (kind in ('input', 'discovery', 'careers', 'listing', 'detail', 'api')),
  depth                  integer not null default 0 check (depth >= 0),
  page_no                integer check (page_no >= 0),
  outcome                text not null check (char_length(outcome) <= 30),
  http_status            integer check (http_status >= 0),
  attempts               integer not null default 1 check (attempts >= 0),
  records                integer not null default 0 check (records >= 0),
  browser_used           boolean not null default false,
  browser_reason         text check (char_length(browser_reason) <= 200),
  browser_duration_ms    double precision check (browser_duration_ms >= 0),
  browser_outcome        text check (char_length(browser_outcome) <= 30),
  error                  text check (char_length(error) <= 1000),
  fetched_at             timestamptz
);

create index scrape_pages_by_ws_created on careercloud.scrape_pages (workspace_id, created_at desc, id desc);
create index scrape_pages_by_ws_run_id on careercloud.scrape_pages (workspace_id, run_id);
create index scrape_pages_by_ws_kind on careercloud.scrape_pages (workspace_id, kind);
create index scrape_pages_by_ws_outcome on careercloud.scrape_pages (workspace_id, outcome);
create unique index scrape_pages_uq_run_id_url_key on careercloud.scrape_pages (workspace_id, run_id, url_key);
create trigger scrape_pages_guard before update on careercloud.scrape_pages
  for each row execute function careercloud.guard_platform_row();
alter table careercloud.scrape_pages enable row level security;
create policy scrape_pages_select on careercloud.scrape_pages for select to authenticated
  using (careercloud.is_member(workspace_id));
create policy scrape_pages_insert on careercloud.scrape_pages for insert to authenticated
  with check (careercloud.can_write(workspace_id) and created_by = auth.uid());
create policy scrape_pages_update on careercloud.scrape_pages for update to authenticated
  using (careercloud.can_write(workspace_id)) with check (careercloud.can_write(workspace_id));
create policy scrape_pages_delete on careercloud.scrape_pages for delete to authenticated
  using (careercloud.can_write(workspace_id));
grant select, insert, update, delete on careercloud.scrape_pages to authenticated;

-- ---------------------------------------------------------------------------
-- Saved scraper templates: instruction, edited schema and run options.
create table careercloud.scrape_templates (
  id                     text primary key check (id ~ '^stp_[0-9a-f]{32}$'),
  workspace_id           uuid not null references careercloud.workspaces (id) on delete cascade,
  created_at             timestamptz not null default now(),
  updated_at             timestamptz not null default now(),
  created_by             uuid,
  version                integer not null default 1,
  name                   text not null check (char_length(name) <= 200),
  description            text check (char_length(description) <= 1000),
  category               text check (char_length(category) <= 60),
  instruction            text not null check (char_length(instruction) <= 4000),
  schema                 jsonb not null default '{}'::jsonb,
  options                jsonb not null default '{}'::jsonb
);

create index scrape_templates_by_ws_created on careercloud.scrape_templates (workspace_id, created_at desc, id desc);
create unique index scrape_templates_uq_name on careercloud.scrape_templates (workspace_id, name);
create trigger scrape_templates_guard before update on careercloud.scrape_templates
  for each row execute function careercloud.guard_platform_row();
alter table careercloud.scrape_templates enable row level security;
create policy scrape_templates_select on careercloud.scrape_templates for select to authenticated
  using (careercloud.is_member(workspace_id));
create policy scrape_templates_insert on careercloud.scrape_templates for insert to authenticated
  with check (careercloud.can_write(workspace_id) and created_by = auth.uid());
create policy scrape_templates_update on careercloud.scrape_templates for update to authenticated
  using (careercloud.can_write(workspace_id)) with check (careercloud.can_write(workspace_id));
create policy scrape_templates_delete on careercloud.scrape_templates for delete to authenticated
  using (careercloud.can_write(workspace_id));
grant select, insert, update, delete on careercloud.scrape_templates to authenticated;

-- ---------------------------------------------------------------------------
-- CRM changes proposed from scraper results. Applied only after a person approves them.
create table careercloud.scrape_proposals (
  id                     text primary key check (id ~ '^spr_[0-9a-f]{32}$'),
  workspace_id           uuid not null references careercloud.workspaces (id) on delete cascade,
  created_at             timestamptz not null default now(),
  updated_at             timestamptz not null default now(),
  created_by             uuid,
  version                integer not null default 1,
  run_id                 text not null check (char_length(run_id) <= 40),
  record_key             text not null check (char_length(record_key) <= 200),
  action                 text not null default 'company' check (action in ('company', 'contact', 'job', 'opportunity', 'task')),
  status                 text not null default 'proposed' check (status in ('proposed', 'approved', 'rejected', 'applied', 'failed')),
  match                  text not null default 'new' check (match in ('new', 'existing', 'possible_duplicate', 'conflict')),
  match_company_id       text check (char_length(match_company_id) <= 40),
  match_reasons          jsonb not null default '[]'::jsonb,
  payload                jsonb not null default '{}'::jsonb,
  applied_entity_type    text check (char_length(applied_entity_type) <= 40),
  applied_entity_id      text check (char_length(applied_entity_id) <= 40),
  error                  text check (char_length(error) <= 1000),
  reviewed_at            timestamptz
);

create index scrape_proposals_by_ws_created on careercloud.scrape_proposals (workspace_id, created_at desc, id desc);
create index scrape_proposals_by_ws_run_id on careercloud.scrape_proposals (workspace_id, run_id);
create index scrape_proposals_by_ws_action on careercloud.scrape_proposals (workspace_id, action);
create index scrape_proposals_by_ws_status on careercloud.scrape_proposals (workspace_id, status);
create index scrape_proposals_by_ws_match on careercloud.scrape_proposals (workspace_id, match);
create unique index scrape_proposals_uq_run_id_record_key_action on careercloud.scrape_proposals (workspace_id, run_id, record_key, action);
create trigger scrape_proposals_guard before update on careercloud.scrape_proposals
  for each row execute function careercloud.guard_platform_row();
alter table careercloud.scrape_proposals enable row level security;
create policy scrape_proposals_select on careercloud.scrape_proposals for select to authenticated
  using (careercloud.is_member(workspace_id));
create policy scrape_proposals_insert on careercloud.scrape_proposals for insert to authenticated
  with check (careercloud.can_write(workspace_id) and created_by = auth.uid());
create policy scrape_proposals_update on careercloud.scrape_proposals for update to authenticated
  using (careercloud.can_write(workspace_id)) with check (careercloud.can_write(workspace_id));
create policy scrape_proposals_delete on careercloud.scrape_proposals for delete to authenticated
  using (careercloud.can_write(workspace_id));
grant select, insert, update, delete on careercloud.scrape_proposals to authenticated;

-- ---------------------------------------------------------------------------
-- Supabase's anonymous role gets nothing in this schema.
-- ---------------------------------------------------------------------------

do $anon$
begin
  if exists (select 1 from pg_roles where rolname = 'anon') then
    revoke all on all tables in schema careercloud from anon;
    revoke all on all functions in schema careercloud from anon;
  end if;
end
$anon$;
