-- GENERATED by `python -m cloud.intel.store.ddl --write` from cloud/intel/store/spec.py.
-- Do not edit by hand: change the specs and regenerate before this migration is
-- applied anywhere; after that, write a new migration.
--
-- SANA GTM completion: email validation jobs, connected mailboxes and the
-- outbound queue, normalized provider events, scoped suppression, teams,
-- invitations and the manager role, notifications, saved reports, explainable
-- score snapshots, integration deliveries, workflow graphs/approvals, and
-- internal-data schema comparison. Same tenancy and RLS model as 0003.

-- ---------------------------------------------------------------------------
-- import_rows.status: widened choices
alter table careercloud.import_rows drop constraint import_rows_status_check,
  add constraint import_rows_status_check check (status in ('pending', 'merged', 'duplicate', 'rejected', 'conflict', 'needs_review'));
-- provider_connections.kind: widened choices
alter table careercloud.provider_connections drop constraint provider_connections_kind_check,
  add constraint provider_connections_kind_check check (kind in ('source', 'enrichment', 'technology', 'email_validation', 'ai', 'sender', 'scraper', 'integration', 'calendar', 'messaging', 'webhook', 'mailbox'));
-- sequence_steps.channel: widened choices
alter table careercloud.sequence_steps drop constraint sequence_steps_channel_check,
  add constraint sequence_steps_channel_check check (channel in ('email', 'task', 'call', 'linkedin_task', 'wait'));
-- sequence_enrollments.status: widened choices
alter table careercloud.sequence_enrollments drop constraint sequence_enrollments_status_check,
  add constraint sequence_enrollments_status_check check (status in ('pending_approval', 'active', 'paused', 'completed', 'replied', 'bounced', 'unsubscribed', 'suppressed', 'stopped', 'failed'));
-- message_events.event: widened choices
alter table careercloud.message_events drop constraint message_events_event_check,
  add constraint message_events_event_check check (event in ('queued', 'rendered', 'sent', 'delivered', 'opened', 'replied', 'bounced', 'unsubscribed', 'blocked', 'failed', 'deferred', 'clicked', 'complained', 'scheduled', 'cancelled'));
-- suppressions.reason: widened choices
alter table careercloud.suppressions drop constraint suppressions_reason_check,
  add constraint suppressions_reason_check check (reason in ('unsubscribe', 'bounce', 'complaint', 'manual', 'legal', 'customer', 'hard_bounce', 'invalid', 'blocked', 'role_policy'));
-- workflow_runs.status: widened choices
alter table careercloud.workflow_runs drop constraint workflow_runs_status_check,
  add constraint workflow_runs_status_check check (status in ('pending', 'running', 'succeeded', 'failed', 'skipped', 'waiting', 'awaiting_approval', 'cancelled'));
-- platform_tasks.kind: widened choices
alter table careercloud.platform_tasks drop constraint platform_tasks_kind_check,
  add constraint platform_tasks_kind_check check (kind in ('crawl', 'discovery', 'scraper', 'enrichment', 'validation', 'research', 'analytics', 'workflow', 'import_merge', 'monitor', 'signals', 'export', 'source_search', 'email_validation_job', 'email_send', 'workflow_resume', 'scoring', 'internal_data', 'integration'));

-- ---------------------------------------------------------------------------
alter table careercloud.companies add column technology_score       double precision check (technology_score >= 0 and technology_score <= 100);
alter table careercloud.companies add column buying_stage           text check (char_length(buying_stage) <= 40);
create index companies_by_ws_buying_stage on careercloud.companies (workspace_id, buying_stage);
alter table careercloud.companies add column buying_stage_score     double precision check (buying_stage_score >= 0 and buying_stage_score <= 100);
alter table careercloud.companies add column scored_at              timestamptz;
alter table careercloud.contacts add column scored_at              timestamptz;
alter table careercloud.import_batches add column schema_report          jsonb not null default '{}'::jsonb;
alter table careercloud.import_batches add column conflict_count         integer not null default 0 check (conflict_count >= 0);
alter table careercloud.import_files add column mapping                jsonb not null default '{}'::jsonb;
alter table careercloud.import_files add column schema_signature       text check (char_length(schema_signature) <= 64);
alter table careercloud.import_rows add column conflicts              jsonb not null default '[]'::jsonb;
alter table careercloud.campaigns add column audience               jsonb not null default '{}'::jsonb;
alter table careercloud.campaigns add column mailbox_ids            text[] not null default '{}'::text[];
alter table careercloud.campaigns add column template_ids           text[] not null default '{}'::text[];
alter table careercloud.campaigns add column schedule               jsonb not null default '{}'::jsonb;
alter table careercloud.campaigns add column approval_policy        text not null default 'manual' check (approval_policy in ('manual', 'auto_after_review'));
alter table careercloud.campaigns add column list_id                text check (char_length(list_id) <= 40);
alter table careercloud.campaigns add column stats                  jsonb not null default '{}'::jsonb;
alter table careercloud.campaigns add column owner_id               uuid;
create index campaigns_by_ws_owner_id on careercloud.campaigns (workspace_id, owner_id);
alter table careercloud.sequences add column stop_conditions        jsonb not null default '{}'::jsonb;
alter table careercloud.sequences add column schedule               jsonb not null default '{}'::jsonb;
alter table careercloud.sequences add column mailbox_id             text check (char_length(mailbox_id) <= 40);
alter table careercloud.sequence_steps add column step_type              text not null default 'initial' check (step_type in ('initial', 'follow_up', 'final', 'wait', 'task'));
alter table careercloud.sequence_steps add column subject_override       text check (char_length(subject_override) <= 500);
alter table careercloud.sequence_steps add column condition              jsonb not null default '{}'::jsonb;
alter table careercloud.sequence_enrollments add column mailbox_id             text check (char_length(mailbox_id) <= 40);
alter table careercloud.sequence_enrollments add column stop_reason            text check (char_length(stop_reason) <= 300);
alter table careercloud.sequence_enrollments add column last_event_at          timestamptz;
alter table careercloud.message_events add column mailbox_id             text check (char_length(mailbox_id) <= 40);
create index message_events_by_ws_mailbox_id on careercloud.message_events (workspace_id, mailbox_id);
alter table careercloud.message_events add column normalized_from        text check (char_length(normalized_from) <= 60);
alter table careercloud.suppressions add column scope                  text not null default 'workspace' check (scope in ('workspace', 'campaign'));
alter table careercloud.suppressions add column campaign_id            text check (char_length(campaign_id) <= 40);
create index suppressions_by_ws_campaign_id on careercloud.suppressions (workspace_id, campaign_id);
alter table careercloud.suppressions add column expires_at             timestamptz;
alter table careercloud.suppressions add column note                   text check (char_length(note) <= 1000);
alter table careercloud.workflows add column graph                  jsonb not null default '{}'::jsonb;
alter table careercloud.workflows add column retry_policy           jsonb not null default '{}'::jsonb;
alter table careercloud.workflows add column failure_policy         text not null default 'stop' check (failure_policy in ('stop', 'continue', 'retry'));
alter table careercloud.workflows add column template_key           text check (char_length(template_key) <= 80);
alter table careercloud.workflows add column last_run_at            timestamptz;
alter table careercloud.workflow_runs add column current_node           text check (char_length(current_node) <= 80);
alter table careercloud.workflow_runs add column resume_at              timestamptz;
create index workflow_runs_by_ws_resume_at on careercloud.workflow_runs (workspace_id, resume_at);
alter table careercloud.workflow_runs add column history                jsonb not null default '[]'::jsonb;
alter table careercloud.workflow_runs add column approved_by            uuid;
alter table careercloud.workflow_runs add column approved_at            timestamptz;
alter table careercloud.audit_log add column actor_label            text check (char_length(actor_label) <= 320);

-- ---------------------------------------------------------------------------
-- One email validation run over an uploaded file, a list, contacts or a scrape.
create table careercloud.email_validation_jobs (
  id                     text primary key check (id ~ '^evj_[0-9a-f]{32}$'),
  workspace_id           uuid not null references careercloud.workspaces (id) on delete cascade,
  created_at             timestamptz not null default now(),
  updated_at             timestamptz not null default now(),
  created_by             uuid,
  version                integer not null default 1,
  name                   text not null check (char_length(name) <= 200),
  source_type            text not null default 'upload' check (source_type in ('upload', 'list', 'contacts', 'scrape', 'manual')),
  source_id              text check (char_length(source_id) <= 40),
  filename               text check (char_length(filename) <= 255),
  format                 text not null default 'none' check (format in ('none', 'csv', 'xlsx')),
  size_bytes             bigint check (size_bytes >= 0),
  storage_key            text check (char_length(storage_key) <= 512),
  columns                text[] not null default '{}'::text[],
  email_column           text check (char_length(email_column) <= 200),
  preview                jsonb not null default '[]'::jsonb,
  row_count              integer not null default 0 check (row_count >= 0),
  processed              integer not null default 0 check (processed >= 0),
  counts                 jsonb not null default '{}'::jsonb,
  settings               jsonb not null default '{}'::jsonb,
  status                 text not null default 'uploaded' check (status in ('uploaded', 'ready', 'queued', 'running', 'paused', 'completed', 'cancelled', 'failed')),
  task_id                text check (char_length(task_id) <= 40),
  error                  text check (char_length(error) <= 2000),
  started_at             timestamptz,
  finished_at            timestamptz
);

create index email_validation_jobs_by_ws_created on careercloud.email_validation_jobs (workspace_id, created_at desc, id desc);
create index email_validation_jobs_by_ws_source_type on careercloud.email_validation_jobs (workspace_id, source_type);
create index email_validation_jobs_by_ws_format on careercloud.email_validation_jobs (workspace_id, format);
create index email_validation_jobs_by_ws_status on careercloud.email_validation_jobs (workspace_id, status);
create trigger email_validation_jobs_guard before update on careercloud.email_validation_jobs
  for each row execute function careercloud.guard_platform_row();
alter table careercloud.email_validation_jobs enable row level security;
create policy email_validation_jobs_select on careercloud.email_validation_jobs for select to authenticated
  using (careercloud.is_member(workspace_id));
create policy email_validation_jobs_insert on careercloud.email_validation_jobs for insert to authenticated
  with check (careercloud.can_write(workspace_id) and created_by = auth.uid());
create policy email_validation_jobs_update on careercloud.email_validation_jobs for update to authenticated
  using (careercloud.can_write(workspace_id)) with check (careercloud.can_write(workspace_id));
create policy email_validation_jobs_delete on careercloud.email_validation_jobs for delete to authenticated
  using (careercloud.can_write(workspace_id));
grant select, insert, update, delete on careercloud.email_validation_jobs to authenticated;

-- ---------------------------------------------------------------------------
-- One row of a validation job: the original row, its email and the result.
create table careercloud.email_validation_items (
  id                     text primary key check (id ~ '^evi_[0-9a-f]{32}$'),
  workspace_id           uuid not null references careercloud.workspaces (id) on delete cascade,
  created_at             timestamptz not null default now(),
  updated_at             timestamptz not null default now(),
  created_by             uuid,
  version                integer not null default 1,
  job_id                 text not null check (char_length(job_id) <= 40),
  row_number             integer not null check (row_number >= 0),
  email                  text check (char_length(email) <= 320),
  domain                 text check (char_length(domain) <= 253),
  status                 text not null default 'PENDING' check (status in ('VALID', 'INVALID', 'RISKY', 'UNKNOWN', 'DISPOSABLE', 'ROLE', 'FREE_PROVIDER', 'PENDING')),
  score                  double precision check (score >= 0 and score <= 100),
  provider               text check (char_length(provider) <= 60),
  checks                 jsonb not null default '{}'::jsonb,
  cached                 boolean not null default false,
  validated_at           timestamptz,
  row                    jsonb not null default '{}'::jsonb,
  contact_id             text check (char_length(contact_id) <= 40)
);

create index email_validation_items_by_ws_created on careercloud.email_validation_items (workspace_id, created_at desc, id desc);
create index email_validation_items_by_ws_job_id on careercloud.email_validation_items (workspace_id, job_id);
create index email_validation_items_by_ws_email on careercloud.email_validation_items (workspace_id, email);
create index email_validation_items_by_ws_domain on careercloud.email_validation_items (workspace_id, domain);
create index email_validation_items_by_ws_status on careercloud.email_validation_items (workspace_id, status);
create unique index email_validation_items_uq_job_id_row_number on careercloud.email_validation_items (workspace_id, job_id, row_number);
create trigger email_validation_items_guard before update on careercloud.email_validation_items
  for each row execute function careercloud.guard_platform_row();
alter table careercloud.email_validation_items enable row level security;
create policy email_validation_items_select on careercloud.email_validation_items for select to authenticated
  using (careercloud.is_member(workspace_id));
create policy email_validation_items_insert on careercloud.email_validation_items for insert to authenticated
  with check (careercloud.can_write(workspace_id) and created_by = auth.uid());
create policy email_validation_items_update on careercloud.email_validation_items for update to authenticated
  using (careercloud.can_write(workspace_id)) with check (careercloud.can_write(workspace_id));
create policy email_validation_items_delete on careercloud.email_validation_items for delete to authenticated
  using (careercloud.can_write(workspace_id));
grant select, insert, update, delete on careercloud.email_validation_items to authenticated;

-- ---------------------------------------------------------------------------
-- A connected sending mailbox (OAuth or API/SMTP relay). Mailbox passwords are never stored.
create table careercloud.mailboxes (
  id                     text primary key check (id ~ '^mb_[0-9a-f]{32}$'),
  workspace_id           uuid not null references careercloud.workspaces (id) on delete cascade,
  created_at             timestamptz not null default now(),
  updated_at             timestamptz not null default now(),
  created_by             uuid,
  version                integer not null default 1,
  provider               text not null default 'google' check (provider in ('google', 'microsoft365', 'smtp', 'api')),
  address                text not null check (char_length(address) <= 320),
  display_name           text check (char_length(display_name) <= 200),
  status                 text not null default 'pending' check (status in ('pending', 'connected', 'error', 'disconnected', 'paused')),
  scopes                 text[] not null default '{}'::text[],
  daily_limit            integer not null default 50 check (daily_limit >= 0 and daily_limit <= 10000),
  hourly_limit           integer not null default 10 check (hourly_limit >= 0 and hourly_limit <= 1000),
  sent_today             integer not null default 0 check (sent_today >= 0),
  sent_day               date,
  last_test_at           timestamptz,
  last_test_result       jsonb not null default '{}'::jsonb,
  health                 text not null default 'unknown' check (health in ('unknown', 'healthy', 'warning', 'failing')),
  is_default             boolean not null default false,
  secret_ciphertext      text check (char_length(secret_ciphertext) <= 8000),
  secret_hint            text check (char_length(secret_hint) <= 40),
  settings               jsonb not null default '{}'::jsonb,
  last_error             text check (char_length(last_error) <= 2000)
);

create index mailboxes_by_ws_created on careercloud.mailboxes (workspace_id, created_at desc, id desc);
create index mailboxes_by_ws_provider on careercloud.mailboxes (workspace_id, provider);
create index mailboxes_by_ws_status on careercloud.mailboxes (workspace_id, status);
create unique index mailboxes_uq_provider_address on careercloud.mailboxes (workspace_id, provider, address);
create trigger mailboxes_guard before update on careercloud.mailboxes
  for each row execute function careercloud.guard_platform_row();
alter table careercloud.mailboxes enable row level security;
create policy mailboxes_select on careercloud.mailboxes for select to authenticated
  using (careercloud.is_member(workspace_id));
create policy mailboxes_insert on careercloud.mailboxes for insert to authenticated
  with check (careercloud.can_write(workspace_id) and created_by = auth.uid());
create policy mailboxes_update on careercloud.mailboxes for update to authenticated
  using (careercloud.can_write(workspace_id)) with check (careercloud.can_write(workspace_id));
create policy mailboxes_delete on careercloud.mailboxes for delete to authenticated
  using (careercloud.can_write(workspace_id));
grant select, insert, update, delete on careercloud.mailboxes to authenticated;

-- ---------------------------------------------------------------------------
-- One pending OAuth authorization (state + PKCE), single use.
create table careercloud.oauth_states (
  id                     text primary key check (id ~ '^oas_[0-9a-f]{32}$'),
  workspace_id           uuid not null references careercloud.workspaces (id) on delete cascade,
  created_at             timestamptz not null default now(),
  updated_at             timestamptz not null default now(),
  created_by             uuid,
  version                integer not null default 1,
  provider               text not null check (char_length(provider) <= 60),
  purpose                text not null check (char_length(purpose) <= 60),
  state_hash             text not null check (char_length(state_hash) <= 64),
  code_verifier_ciphertext text check (char_length(code_verifier_ciphertext) <= 2000),
  redirect_to            text check (char_length(redirect_to) <= 500),
  expires_at             timestamptz not null,
  used_at                timestamptz
);

create index oauth_states_by_ws_created on careercloud.oauth_states (workspace_id, created_at desc, id desc);
create unique index oauth_states_uq_state_hash on careercloud.oauth_states (workspace_id, state_hash);
create trigger oauth_states_guard before update on careercloud.oauth_states
  for each row execute function careercloud.guard_platform_row();
alter table careercloud.oauth_states enable row level security;
create policy oauth_states_select on careercloud.oauth_states for select to authenticated
  using (careercloud.is_member(workspace_id));
create policy oauth_states_insert on careercloud.oauth_states for insert to authenticated
  with check (careercloud.can_write(workspace_id) and created_by = auth.uid());
create policy oauth_states_update on careercloud.oauth_states for update to authenticated
  using (careercloud.can_write(workspace_id)) with check (careercloud.can_write(workspace_id));
create policy oauth_states_delete on careercloud.oauth_states for delete to authenticated
  using (careercloud.can_write(workspace_id));
grant select, insert, update, delete on careercloud.oauth_states to authenticated;

-- ---------------------------------------------------------------------------
-- The outbound queue: every message rendered for sending, and what happened to it.
create table careercloud.outbound_messages (
  id                     text primary key check (id ~ '^om_[0-9a-f]{32}$'),
  workspace_id           uuid not null references careercloud.workspaces (id) on delete cascade,
  created_at             timestamptz not null default now(),
  updated_at             timestamptz not null default now(),
  created_by             uuid,
  version                integer not null default 1,
  campaign_id            text check (char_length(campaign_id) <= 40),
  sequence_id            text check (char_length(sequence_id) <= 40),
  enrollment_id          text check (char_length(enrollment_id) <= 40),
  step                   integer check (step >= 0),
  contact_id             text check (char_length(contact_id) <= 40),
  mailbox_id             text check (char_length(mailbox_id) <= 40),
  to_email               text not null check (char_length(to_email) <= 320),
  subject                text not null check (char_length(subject) <= 1000),
  body                   text not null check (char_length(body) <= 50000),
  status                 text not null default 'queued' check (status in ('queued', 'scheduled', 'sending', 'sent', 'blocked', 'failed', 'cancelled')),
  scheduled_for          timestamptz,
  sent_at                timestamptz,
  provider               text check (char_length(provider) <= 60),
  provider_message_id    text check (char_length(provider_message_id) <= 300),
  attempts               integer not null default 0 check (attempts >= 0),
  block_reason           text check (char_length(block_reason) <= 500),
  error                  text check (char_length(error) <= 2000),
  test                   boolean not null default false
);

create index outbound_messages_by_ws_created on careercloud.outbound_messages (workspace_id, created_at desc, id desc);
create index outbound_messages_by_ws_campaign_id on careercloud.outbound_messages (workspace_id, campaign_id);
create index outbound_messages_by_ws_enrollment_id on careercloud.outbound_messages (workspace_id, enrollment_id);
create index outbound_messages_by_ws_contact_id on careercloud.outbound_messages (workspace_id, contact_id);
create index outbound_messages_by_ws_mailbox_id on careercloud.outbound_messages (workspace_id, mailbox_id);
create index outbound_messages_by_ws_status on careercloud.outbound_messages (workspace_id, status);
create index outbound_messages_by_ws_scheduled_for on careercloud.outbound_messages (workspace_id, scheduled_for);
create index outbound_messages_by_ws_provider_message_id on careercloud.outbound_messages (workspace_id, provider_message_id);
create trigger outbound_messages_guard before update on careercloud.outbound_messages
  for each row execute function careercloud.guard_platform_row();
alter table careercloud.outbound_messages enable row level security;
create policy outbound_messages_select on careercloud.outbound_messages for select to authenticated
  using (careercloud.is_member(workspace_id));
create policy outbound_messages_insert on careercloud.outbound_messages for insert to authenticated
  with check (careercloud.can_write(workspace_id) and created_by = auth.uid());
create policy outbound_messages_update on careercloud.outbound_messages for update to authenticated
  using (careercloud.can_write(workspace_id)) with check (careercloud.can_write(workspace_id));
create policy outbound_messages_delete on careercloud.outbound_messages for delete to authenticated
  using (careercloud.can_write(workspace_id));
grant select, insert, update, delete on careercloud.outbound_messages to authenticated;

-- ---------------------------------------------------------------------------
-- Provider webhook events, normalized and de-duplicated before they change anything.
create table careercloud.inbound_events (
  id                     text primary key check (id ~ '^ine_[0-9a-f]{32}$'),
  workspace_id           uuid not null references careercloud.workspaces (id) on delete cascade,
  created_at             timestamptz not null default now(),
  updated_at             timestamptz not null default now(),
  created_by             uuid,
  version                integer not null default 1,
  provider               text not null check (char_length(provider) <= 60),
  provider_event_id      text not null check (char_length(provider_event_id) <= 300),
  kind                   text not null default 'delivered' check (kind in ('delivered', 'bounced', 'deferred', 'opened', 'clicked', 'replied', 'unsubscribed', 'complained', 'unknown')),
  bounce_type            text not null default 'none' check (bounce_type in ('none', 'hard', 'soft')),
  email                  text check (char_length(email) <= 320),
  provider_message_id    text check (char_length(provider_message_id) <= 300),
  occurred_at            timestamptz not null,
  processed              boolean not null default false,
  result                 jsonb not null default '{}'::jsonb,
  raw                    jsonb not null default '{}'::jsonb
);

create index inbound_events_by_ws_created on careercloud.inbound_events (workspace_id, created_at desc, id desc);
create index inbound_events_by_ws_provider on careercloud.inbound_events (workspace_id, provider);
create index inbound_events_by_ws_kind on careercloud.inbound_events (workspace_id, kind);
create index inbound_events_by_ws_email on careercloud.inbound_events (workspace_id, email);
create unique index inbound_events_uq_provider_provider_event_id on careercloud.inbound_events (workspace_id, provider, provider_event_id);
create trigger inbound_events_guard before update on careercloud.inbound_events
  for each row execute function careercloud.guard_platform_row();
alter table careercloud.inbound_events enable row level security;
create policy inbound_events_select on careercloud.inbound_events for select to authenticated
  using (careercloud.is_member(workspace_id));
create policy inbound_events_insert on careercloud.inbound_events for insert to authenticated
  with check (careercloud.can_write(workspace_id) and created_by = auth.uid());
create policy inbound_events_update on careercloud.inbound_events for update to authenticated
  using (careercloud.can_write(workspace_id)) with check (careercloud.can_write(workspace_id));
create policy inbound_events_delete on careercloud.inbound_events for delete to authenticated
  using (careercloud.can_write(workspace_id));
grant select, insert, update, delete on careercloud.inbound_events to authenticated;

-- ---------------------------------------------------------------------------
-- teams
create table careercloud.teams (
  id                     text primary key check (id ~ '^tm_[0-9a-f]{32}$'),
  workspace_id           uuid not null references careercloud.workspaces (id) on delete cascade,
  created_at             timestamptz not null default now(),
  updated_at             timestamptz not null default now(),
  created_by             uuid,
  version                integer not null default 1,
  name                   text not null check (char_length(name) <= 120),
  description            text check (char_length(description) <= 1000),
  lead_user_id           uuid
);

create index teams_by_ws_created on careercloud.teams (workspace_id, created_at desc, id desc);
create unique index teams_uq_name on careercloud.teams (workspace_id, name);
create trigger teams_guard before update on careercloud.teams
  for each row execute function careercloud.guard_platform_row();
alter table careercloud.teams enable row level security;
create policy teams_select on careercloud.teams for select to authenticated
  using (careercloud.is_member(workspace_id));
create policy teams_insert on careercloud.teams for insert to authenticated
  with check (careercloud.can_write(workspace_id) and created_by = auth.uid());
create policy teams_update on careercloud.teams for update to authenticated
  using (careercloud.can_write(workspace_id)) with check (careercloud.can_write(workspace_id));
create policy teams_delete on careercloud.teams for delete to authenticated
  using (careercloud.can_write(workspace_id));
grant select, insert, update, delete on careercloud.teams to authenticated;

-- ---------------------------------------------------------------------------
-- team_members
create table careercloud.team_members (
  id                     text primary key check (id ~ '^tmm_[0-9a-f]{32}$'),
  workspace_id           uuid not null references careercloud.workspaces (id) on delete cascade,
  created_at             timestamptz not null default now(),
  updated_at             timestamptz not null default now(),
  created_by             uuid,
  version                integer not null default 1,
  team_id                text not null check (char_length(team_id) <= 40),
  user_id                uuid not null,
  role                   text not null default 'member' check (role in ('member', 'lead'))
);

create index team_members_by_ws_created on careercloud.team_members (workspace_id, created_at desc, id desc);
create index team_members_by_ws_team_id on careercloud.team_members (workspace_id, team_id);
create index team_members_by_ws_user_id on careercloud.team_members (workspace_id, user_id);
create index team_members_by_ws_role on careercloud.team_members (workspace_id, role);
create unique index team_members_uq_team_id_user_id on careercloud.team_members (workspace_id, team_id, user_id);
create trigger team_members_guard before update on careercloud.team_members
  for each row execute function careercloud.guard_platform_row();
alter table careercloud.team_members enable row level security;
create policy team_members_select on careercloud.team_members for select to authenticated
  using (careercloud.is_member(workspace_id));
create policy team_members_insert on careercloud.team_members for insert to authenticated
  with check (careercloud.can_write(workspace_id) and created_by = auth.uid());
create policy team_members_update on careercloud.team_members for update to authenticated
  using (careercloud.can_write(workspace_id)) with check (careercloud.can_write(workspace_id));
create policy team_members_delete on careercloud.team_members for delete to authenticated
  using (careercloud.can_write(workspace_id));
grant select, insert, update, delete on careercloud.team_members to authenticated;

-- ---------------------------------------------------------------------------
-- workspace_invitations
create table careercloud.workspace_invitations (
  id                     text primary key check (id ~ '^inv_[0-9a-f]{32}$'),
  workspace_id           uuid not null references careercloud.workspaces (id) on delete cascade,
  created_at             timestamptz not null default now(),
  updated_at             timestamptz not null default now(),
  created_by             uuid,
  version                integer not null default 1,
  email                  text not null check (char_length(email) <= 320),
  role                   text not null default 'member' check (role in ('member', 'manager', 'admin', 'viewer')),
  status                 text not null default 'pending' check (status in ('pending', 'accepted', 'revoked', 'expired')),
  token_hash             text not null check (char_length(token_hash) <= 64),
  expires_at             timestamptz not null,
  accepted_at            timestamptz,
  accepted_by            uuid
);

create index workspace_invitations_by_ws_created on careercloud.workspace_invitations (workspace_id, created_at desc, id desc);
create index workspace_invitations_by_ws_role on careercloud.workspace_invitations (workspace_id, role);
create index workspace_invitations_by_ws_status on careercloud.workspace_invitations (workspace_id, status);
create unique index workspace_invitations_uq_token_hash on careercloud.workspace_invitations (workspace_id, token_hash);
create trigger workspace_invitations_guard before update on careercloud.workspace_invitations
  for each row execute function careercloud.guard_platform_row();
alter table careercloud.workspace_invitations enable row level security;
create policy workspace_invitations_select on careercloud.workspace_invitations for select to authenticated
  using (careercloud.is_member(workspace_id));
create policy workspace_invitations_insert on careercloud.workspace_invitations for insert to authenticated
  with check (careercloud.can_write(workspace_id) and created_by = auth.uid());
create policy workspace_invitations_update on careercloud.workspace_invitations for update to authenticated
  using (careercloud.can_write(workspace_id)) with check (careercloud.can_write(workspace_id));
create policy workspace_invitations_delete on careercloud.workspace_invitations for delete to authenticated
  using (careercloud.can_write(workspace_id));
grant select, insert, update, delete on careercloud.workspace_invitations to authenticated;

-- ---------------------------------------------------------------------------
-- notifications
create table careercloud.notifications (
  id                     text primary key check (id ~ '^nf_[0-9a-f]{32}$'),
  workspace_id           uuid not null references careercloud.workspaces (id) on delete cascade,
  created_at             timestamptz not null default now(),
  updated_at             timestamptz not null default now(),
  created_by             uuid,
  version                integer not null default 1,
  user_id                uuid,
  kind                   text not null check (char_length(kind) <= 60),
  title                  text not null check (char_length(title) <= 300),
  body                   text check (char_length(body) <= 2000),
  link                   text check (char_length(link) <= 500),
  severity               text not null default 'info' check (severity in ('info', 'success', 'warning', 'error')),
  entity_type            text check (char_length(entity_type) <= 40),
  entity_id              text check (char_length(entity_id) <= 40),
  read_at                timestamptz
);

create index notifications_by_ws_created on careercloud.notifications (workspace_id, created_at desc, id desc);
create index notifications_by_ws_user_id on careercloud.notifications (workspace_id, user_id);
create index notifications_by_ws_kind on careercloud.notifications (workspace_id, kind);
create index notifications_by_ws_severity on careercloud.notifications (workspace_id, severity);
create trigger notifications_guard before update on careercloud.notifications
  for each row execute function careercloud.guard_platform_row();
alter table careercloud.notifications enable row level security;
create policy notifications_select on careercloud.notifications for select to authenticated
  using (careercloud.is_member(workspace_id));
create policy notifications_insert on careercloud.notifications for insert to authenticated
  with check (careercloud.can_write(workspace_id) and created_by = auth.uid());
create policy notifications_update on careercloud.notifications for update to authenticated
  using (careercloud.can_write(workspace_id)) with check (careercloud.can_write(workspace_id));
create policy notifications_delete on careercloud.notifications for delete to authenticated
  using (careercloud.can_write(workspace_id));
grant select, insert, update, delete on careercloud.notifications to authenticated;

-- ---------------------------------------------------------------------------
-- saved_reports
create table careercloud.saved_reports (
  id                     text primary key check (id ~ '^rpt_[0-9a-f]{32}$'),
  workspace_id           uuid not null references careercloud.workspaces (id) on delete cascade,
  created_at             timestamptz not null default now(),
  updated_at             timestamptz not null default now(),
  created_by             uuid,
  version                integer not null default 1,
  name                   text not null check (char_length(name) <= 200),
  report                 text not null check (char_length(report) <= 60),
  filters                jsonb not null default '{}'::jsonb,
  date_range             jsonb not null default '{}'::jsonb,
  shared                 boolean not null default true
);

create index saved_reports_by_ws_created on careercloud.saved_reports (workspace_id, created_at desc, id desc);
create index saved_reports_by_ws_report on careercloud.saved_reports (workspace_id, report);
create trigger saved_reports_guard before update on careercloud.saved_reports
  for each row execute function careercloud.guard_platform_row();
alter table careercloud.saved_reports enable row level security;
create policy saved_reports_select on careercloud.saved_reports for select to authenticated
  using (careercloud.is_member(workspace_id));
create policy saved_reports_insert on careercloud.saved_reports for insert to authenticated
  with check (careercloud.can_write(workspace_id) and created_by = auth.uid());
create policy saved_reports_update on careercloud.saved_reports for update to authenticated
  using (careercloud.can_write(workspace_id)) with check (careercloud.can_write(workspace_id));
create policy saved_reports_delete on careercloud.saved_reports for delete to authenticated
  using (careercloud.can_write(workspace_id));
grant select, insert, update, delete on careercloud.saved_reports to authenticated;

-- ---------------------------------------------------------------------------
-- Explainable score history: the score, every factor and the evidence behind it.
create table careercloud.score_snapshots (
  id                     text primary key check (id ~ '^scs_[0-9a-f]{32}$'),
  workspace_id           uuid not null references careercloud.workspaces (id) on delete cascade,
  created_at             timestamptz not null default now(),
  updated_at             timestamptz not null default now(),
  created_by             uuid,
  version                integer not null default 1,
  entity_type            text not null default 'company' check (entity_type in ('company', 'contact')),
  entity_id              text not null check (char_length(entity_id) <= 40),
  kind                   text not null default 'account' check (kind in ('account', 'contact', 'hiring', 'technology', 'opportunity', 'buying_stage')),
  score                  double precision check (score >= 0 and score <= 100),
  label                  text check (char_length(label) <= 60),
  factors                jsonb not null default '[]'::jsonb,
  evidence               jsonb not null default '[]'::jsonb,
  model                  text not null check (char_length(model) <= 60),
  computed_at            timestamptz not null
);

create index score_snapshots_by_ws_created on careercloud.score_snapshots (workspace_id, created_at desc, id desc);
create index score_snapshots_by_ws_entity_type on careercloud.score_snapshots (workspace_id, entity_type);
create index score_snapshots_by_ws_entity_id on careercloud.score_snapshots (workspace_id, entity_id);
create index score_snapshots_by_ws_kind on careercloud.score_snapshots (workspace_id, kind);
create trigger score_snapshots_guard before update on careercloud.score_snapshots
  for each row execute function careercloud.guard_platform_row();
alter table careercloud.score_snapshots enable row level security;
create policy score_snapshots_select on careercloud.score_snapshots for select to authenticated
  using (careercloud.is_member(workspace_id));
create policy score_snapshots_insert on careercloud.score_snapshots for insert to authenticated
  with check (careercloud.can_write(workspace_id) and created_by = auth.uid());
grant select, insert on careercloud.score_snapshots to authenticated;

-- ---------------------------------------------------------------------------
-- Outbound integration calls (Slack, webhooks, calendar) and their outcome.
create table careercloud.integration_deliveries (
  id                     text primary key check (id ~ '^idl_[0-9a-f]{32}$'),
  workspace_id           uuid not null references careercloud.workspaces (id) on delete cascade,
  created_at             timestamptz not null default now(),
  updated_at             timestamptz not null default now(),
  created_by             uuid,
  version                integer not null default 1,
  provider               text not null check (char_length(provider) <= 60),
  event                  text not null check (char_length(event) <= 100),
  target                 text check (char_length(target) <= 500),
  status                 text not null default 'queued' check (status in ('queued', 'delivered', 'failed', 'skipped', 'mocked')),
  attempts               integer not null default 0 check (attempts >= 0),
  response_code          integer,
  error                  text check (char_length(error) <= 2000),
  payload                jsonb not null default '{}'::jsonb
);

create index integration_deliveries_by_ws_created on careercloud.integration_deliveries (workspace_id, created_at desc, id desc);
create index integration_deliveries_by_ws_provider on careercloud.integration_deliveries (workspace_id, provider);
create index integration_deliveries_by_ws_status on careercloud.integration_deliveries (workspace_id, status);
create trigger integration_deliveries_guard before update on careercloud.integration_deliveries
  for each row execute function careercloud.guard_platform_row();
alter table careercloud.integration_deliveries enable row level security;
create policy integration_deliveries_select on careercloud.integration_deliveries for select to authenticated
  using (careercloud.is_member(workspace_id));
create policy integration_deliveries_insert on careercloud.integration_deliveries for insert to authenticated
  with check (careercloud.can_write(workspace_id) and created_by = auth.uid());
create policy integration_deliveries_update on careercloud.integration_deliveries for update to authenticated
  using (careercloud.can_write(workspace_id)) with check (careercloud.can_write(workspace_id));
create policy integration_deliveries_delete on careercloud.integration_deliveries for delete to authenticated
  using (careercloud.can_write(workspace_id));
grant select, insert, update, delete on careercloud.integration_deliveries to authenticated;

-- ---------------------------------------------------------------------------
-- CRM changes proposed by workflows (PROPOSE -> REVIEW -> APPLY).
create table careercloud.workflow_proposals (
  id                     text primary key check (id ~ '^wpr_[0-9a-f]{32}$'),
  workspace_id           uuid not null references careercloud.workspaces (id) on delete cascade,
  created_at             timestamptz not null default now(),
  updated_at             timestamptz not null default now(),
  created_by             uuid,
  version                integer not null default 1,
  workflow_id            text not null check (char_length(workflow_id) <= 40),
  run_id                 text not null check (char_length(run_id) <= 40),
  node                   text not null check (char_length(node) <= 80),
  action                 text not null default 'update_company' check (action in ('update_company', 'update_contact')),
  entity_type            text not null default 'companies' check (entity_type in ('companies', 'contacts')),
  entity_id              text not null check (char_length(entity_id) <= 40),
  changes                jsonb not null default '{}'::jsonb,
  reason                 text check (char_length(reason) <= 1000),
  status                 text not null default 'proposed' check (status in ('proposed', 'approved', 'rejected', 'applied', 'failed')),
  reviewed_by            uuid,
  reviewed_at            timestamptz,
  error                  text check (char_length(error) <= 1000)
);

create index workflow_proposals_by_ws_created on careercloud.workflow_proposals (workspace_id, created_at desc, id desc);
create index workflow_proposals_by_ws_workflow_id on careercloud.workflow_proposals (workspace_id, workflow_id);
create index workflow_proposals_by_ws_run_id on careercloud.workflow_proposals (workspace_id, run_id);
create index workflow_proposals_by_ws_action on careercloud.workflow_proposals (workspace_id, action);
create index workflow_proposals_by_ws_entity_type on careercloud.workflow_proposals (workspace_id, entity_type);
create index workflow_proposals_by_ws_status on careercloud.workflow_proposals (workspace_id, status);
create unique index workflow_proposals_uq_run_id_node on careercloud.workflow_proposals (workspace_id, run_id, node);
create trigger workflow_proposals_guard before update on careercloud.workflow_proposals
  for each row execute function careercloud.guard_platform_row();
alter table careercloud.workflow_proposals enable row level security;
create policy workflow_proposals_select on careercloud.workflow_proposals for select to authenticated
  using (careercloud.is_member(workspace_id));
create policy workflow_proposals_insert on careercloud.workflow_proposals for insert to authenticated
  with check (careercloud.can_write(workspace_id) and created_by = auth.uid());
create policy workflow_proposals_update on careercloud.workflow_proposals for update to authenticated
  using (careercloud.can_write(workspace_id)) with check (careercloud.can_write(workspace_id));
create policy workflow_proposals_delete on careercloud.workflow_proposals for delete to authenticated
  using (careercloud.can_write(workspace_id));
grant select, insert, update, delete on careercloud.workflow_proposals to authenticated;

-- ---------------------------------------------------------------------------
-- Tenancy: the manager role (writes like a member, manages teams/assignment).
-- ---------------------------------------------------------------------------

alter table careercloud.workspace_members drop constraint workspace_members_role_check,
  add constraint workspace_members_role_check check (role in ('owner', 'admin', 'manager', 'member', 'viewer'));

create or replace function careercloud.can_write(ws uuid) returns boolean
  language sql stable
  as $fn$ select coalesce(careercloud.member_role(ws) in ('owner', 'admin', 'manager', 'member'), false) $fn$;

-- ---------------------------------------------------------------------------
-- Supabase's anonymous role gets nothing in this schema.
-- ---------------------------------------------------------------------------

do $anon$
begin
  if exists (select 1 from pg_roles where rolname = 'anon') then
    revoke all on all tables in schema careercloud from anon;
    revoke all on all functions in schema careercloud from anon;
  end if;
end
$anon$;
