-- GENERATED by `python -m cloud.intel.store.ddl --write` from cloud/intel/store/spec.py.
-- Do not edit by hand: change the specs and regenerate before this migration is
-- applied anywhere; after that, write a new migration.
--
-- Email validation evidence cache: DNS/MX, SPF/DMARC, SMTP preflight, public-web
-- evidence and catch-all results keyed by a SHA-256 of the address, domain or host
-- (never the plain address), each with its own expiry. Same tenancy and RLS model as 0003.

-- ---------------------------------------------------------------------------
-- Reusable email-validation evidence (DNS, SPF/DMARC, SMTP preflight, public evidence, catch-all) keyed by a SHA-256 of the address, domain or host, with a per-check expiry.
create table careercloud.email_check_cache (
  id                     text primary key check (id ~ '^ecc_[0-9a-f]{32}$'),
  workspace_id           uuid not null references careercloud.workspaces (id) on delete cascade,
  created_at             timestamptz not null default now(),
  updated_at             timestamptz not null default now(),
  created_by             uuid,
  version                integer not null default 1,
  subject_hash           text not null check (char_length(subject_hash) <= 64),
  subject_kind           text not null default 'email' check (subject_kind in ('email', 'domain', 'host')),
  check_type             text not null check (char_length(check_type) <= 40),
  result                 jsonb not null default '{}'::jsonb,
  source                 text check (char_length(source) <= 60),
  provider               text check (char_length(provider) <= 60),
  provider_ref           text check (char_length(provider_ref) <= 200),
  checked_at             timestamptz not null,
  expires_at             timestamptz not null
);

create index email_check_cache_by_ws_created on careercloud.email_check_cache (workspace_id, created_at desc, id desc);
create index email_check_cache_by_ws_subject_hash on careercloud.email_check_cache (workspace_id, subject_hash);
create index email_check_cache_by_ws_subject_kind on careercloud.email_check_cache (workspace_id, subject_kind);
create index email_check_cache_by_ws_check_type on careercloud.email_check_cache (workspace_id, check_type);
create index email_check_cache_by_ws_expires_at on careercloud.email_check_cache (workspace_id, expires_at);
create unique index email_check_cache_uq_subject_hash_check_type on careercloud.email_check_cache (workspace_id, subject_hash, check_type);
create trigger email_check_cache_guard before update on careercloud.email_check_cache
  for each row execute function careercloud.guard_platform_row();
alter table careercloud.email_check_cache enable row level security;
create policy email_check_cache_select on careercloud.email_check_cache for select to authenticated
  using (careercloud.is_member(workspace_id));
create policy email_check_cache_insert on careercloud.email_check_cache for insert to authenticated
  with check (careercloud.can_write(workspace_id) and created_by = auth.uid());
create policy email_check_cache_update on careercloud.email_check_cache for update to authenticated
  using (careercloud.can_write(workspace_id)) with check (careercloud.can_write(workspace_id));
create policy email_check_cache_delete on careercloud.email_check_cache for delete to authenticated
  using (careercloud.can_write(workspace_id));
grant select, insert, update, delete on careercloud.email_check_cache to authenticated;

-- ---------------------------------------------------------------------------
-- Supabase's anonymous role gets nothing in this schema.
-- ---------------------------------------------------------------------------

do $anon$
begin
  if exists (select 1 from pg_roles where rolname = 'anon') then
    revoke all on all tables in schema careercloud from anon;
    revoke all on all functions in schema careercloud from anon;
  end if;
end
$anon$;
