-- GENERATED by `python -m cloud.intel.store.ddl --write` from cloud/intel/store/spec.py.
-- Do not edit by hand: change the specs and regenerate before this migration is
-- applied anywhere; after that, write a new migration.
--
-- User invitations: invitee name, team to join, inviter label and delivery
-- bookkeeping on workspace_invitations, and its RLS narrowed to workspace admins
-- (owner/admin), because the rows hold invitee emails and token hashes. The
-- invitation token itself is never stored.

-- ---------------------------------------------------------------------------
alter table careercloud.workspace_invitations add column first_name             text check (char_length(first_name) <= 100);
alter table careercloud.workspace_invitations add column last_name              text check (char_length(last_name) <= 100);
alter table careercloud.workspace_invitations add column team_id                text check (char_length(team_id) <= 40);
alter table careercloud.workspace_invitations add column invited_by_label       text check (char_length(invited_by_label) <= 320);
alter table careercloud.workspace_invitations add column delivery               text not null default 'link' check (delivery in ('link', 'email', 'email_failed'));
alter table careercloud.workspace_invitations add column sent_count             integer not null default 0 check (sent_count >= 0);
alter table careercloud.workspace_invitations add column last_sent_at           timestamptz;
alter table careercloud.workspace_invitations add column revoked_at             timestamptz;
alter table careercloud.workspace_invitations add column revoked_by             uuid;

-- ---------------------------------------------------------------------------
-- workspace_invitations: workspace admins only
drop policy workspace_invitations_select on careercloud.workspace_invitations;
drop policy workspace_invitations_insert on careercloud.workspace_invitations;
drop policy workspace_invitations_update on careercloud.workspace_invitations;
drop policy workspace_invitations_delete on careercloud.workspace_invitations;
create policy workspace_invitations_select on careercloud.workspace_invitations for select to authenticated
  using (careercloud.can_admin(workspace_id));
create policy workspace_invitations_insert on careercloud.workspace_invitations for insert to authenticated
  with check (careercloud.can_admin(workspace_id) and created_by = auth.uid());
create policy workspace_invitations_update on careercloud.workspace_invitations for update to authenticated
  using (careercloud.can_admin(workspace_id)) with check (careercloud.can_admin(workspace_id));
create policy workspace_invitations_delete on careercloud.workspace_invitations for delete to authenticated
  using (careercloud.can_admin(workspace_id));

-- ---------------------------------------------------------------------------
-- Supabase's anonymous role gets nothing in this schema.
-- ---------------------------------------------------------------------------

do $anon$
begin
  if exists (select 1 from pg_roles where rolname = 'anon') then
    revoke all on all tables in schema careercloud from anon;
    revoke all on all functions in schema careercloud from anon;
  end if;
end
$anon$;
