-- GENERATED by `python -m cloud.intel.store.ddl --write` from cloud/intel/store/spec.py.
-- Do not edit by hand: change the specs and regenerate before this migration is
-- applied anywhere; after that, write a new migration.
--
-- Job source monitors: the 14 mandatory job fields on job_postings (experience,
-- salary, keywords 1-5, remote, source, scraped date) plus change tracking
-- (content hash, first/last seen and changed runs, missed full sweeps), the
-- "unknown" posting status, a nullable company name (never invented), saved
-- monitors and their runs, job history, historical job imports and the company
-- review queue. (0010 is reserved for the admin-users branch.) Same tenancy and
-- RLS model as 0003.

-- ---------------------------------------------------------------------------
-- job_postings.status: widened choices
alter table careercloud.job_postings drop constraint job_postings_status_check,
  add constraint job_postings_status_check check (status in ('open', 'closed', 'unknown'));
-- platform_tasks.kind: widened choices
alter table careercloud.platform_tasks drop constraint platform_tasks_kind_check,
  add constraint platform_tasks_kind_check check (kind in ('crawl', 'discovery', 'scraper', 'enrichment', 'validation', 'research', 'analytics', 'workflow', 'import_merge', 'monitor', 'signals', 'export', 'source_search', 'email_validation_job', 'email_send', 'workflow_resume', 'scoring', 'internal_data', 'integration', 'job_monitor', 'job_import'));

-- ---------------------------------------------------------------------------
-- job_postings.company_name: no longer required
alter table careercloud.job_postings alter column company_name drop not null;

-- ---------------------------------------------------------------------------
alter table careercloud.job_postings add column experience_level       text check (char_length(experience_level) <= 100);
alter table careercloud.job_postings add column salary_budget          text check (char_length(salary_budget) <= 200);
alter table careercloud.job_postings add column keyword_1              text check (char_length(keyword_1) <= 200);
alter table careercloud.job_postings add column keyword_2              text check (char_length(keyword_2) <= 200);
alter table careercloud.job_postings add column keyword_3              text check (char_length(keyword_3) <= 200);
alter table careercloud.job_postings add column keyword_4              text check (char_length(keyword_4) <= 200);
alter table careercloud.job_postings add column keyword_5              text check (char_length(keyword_5) <= 200);
alter table careercloud.job_postings add column remote                 text check (char_length(remote) <= 40);
alter table careercloud.job_postings add column source                 text check (char_length(source) <= 200);
create index job_postings_by_ws_source on careercloud.job_postings (workspace_id, source);
alter table careercloud.job_postings add column scraped_date           date;
create index job_postings_by_ws_scraped_date on careercloud.job_postings (workspace_id, scraped_date);
alter table careercloud.job_postings add column last_changed_at        timestamptz;
create index job_postings_by_ws_last_changed_at on careercloud.job_postings (workspace_id, last_changed_at);
alter table careercloud.job_postings add column content_hash           text check (char_length(content_hash) <= 64);
alter table careercloud.job_postings add column source_monitor_id      text check (char_length(source_monitor_id) <= 40);
create index job_postings_by_ws_source_monitor_id on careercloud.job_postings (workspace_id, source_monitor_id);
alter table careercloud.job_postings add column first_seen_run_id      text check (char_length(first_seen_run_id) <= 40);
create index job_postings_by_ws_first_seen_run_id on careercloud.job_postings (workspace_id, first_seen_run_id);
alter table careercloud.job_postings add column last_seen_run_id       text check (char_length(last_seen_run_id) <= 40);
alter table careercloud.job_postings add column last_changed_run_id    text check (char_length(last_changed_run_id) <= 40);
create index job_postings_by_ws_last_changed_run_id on careercloud.job_postings (workspace_id, last_changed_run_id);
alter table careercloud.job_postings add column closed_run_id          text check (char_length(closed_run_id) <= 40);
create index job_postings_by_ws_closed_run_id on careercloud.job_postings (workspace_id, closed_run_id);
alter table careercloud.job_postings add column missed_full_sweeps     integer not null default 0 check (missed_full_sweeps >= 0);
alter table careercloud.job_postings add column missed_run_id          text check (char_length(missed_run_id) <= 40);
alter table careercloud.job_postings add column observation_count      integer not null default 0 check (observation_count >= 0);
alter table careercloud.job_postings add column company_match          text not null default 'unmatched' check (company_match in ('unmatched', 'matched', 'review'));
alter table careercloud.job_postings add column source_board           text check (char_length(source_board) <= 100);
create index job_postings_by_ws_source_board on careercloud.job_postings (workspace_id, source_board);
alter table careercloud.job_postings add column search_term            text check (char_length(search_term) <= 300);
alter table careercloud.job_postings add column matched_keywords       text[] not null default '{}'::text[];
alter table careercloud.job_postings add column matched_categories     text[] not null default '{}'::text[];
alter table careercloud.job_postings add column relevance_score        double precision check (relevance_score >= 0 and relevance_score <= 100);
create index job_postings_by_ws_relevance_score on careercloud.job_postings (workspace_id, relevance_score);
alter table careercloud.job_postings add column relevance_class        text check (relevance_class in ('HIGH', 'REVIEW', 'REJECT'));
create index job_postings_by_ws_relevance_class on careercloud.job_postings (workspace_id, relevance_class);
alter table careercloud.job_postings add column relevance_reason       text check (char_length(relevance_reason) <= 1000);
alter table careercloud.job_postings add column relevance_version      text check (char_length(relevance_version) <= 80);

-- ---------------------------------------------------------------------------
-- A saved, scheduled job source: where to read, how (strategy + site profile), which fields, and how often; runs feed job_postings.
create table careercloud.job_source_monitors (
  id                     text primary key check (id ~ '^jmon_[0-9a-f]{32}$'),
  workspace_id           uuid not null references careercloud.workspaces (id) on delete cascade,
  created_at             timestamptz not null default now(),
  updated_at             timestamptz not null default now(),
  created_by             uuid,
  version                integer not null default 1,
  name                   text not null check (char_length(name) <= 200),
  source_url             text not null check (char_length(source_url) <= 2048),
  source_name            text not null check (char_length(source_name) <= 200),
  source_type            text not null default 'job_board' check (source_type in ('job_board', 'company_careers', 'ats_api', 'feed')),
  strategy               text not null default 'wad_turbo' check (strategy in ('wad_turbo', 'site_profile', 'ai_scraper', 'jobspy')),
  profile                text check (char_length(profile) <= 60),
  filters                jsonb not null default '{}'::jsonb,
  extraction_schema      jsonb not null default '[]'::jsonb,
  schedule               text not null default 'daily' check (schedule in ('daily', 'weekly', 'manual')),
  full_sweep_days        integer not null default 7 check (full_sweep_days >= 1 and full_sweep_days <= 90),
  close_after_missed     integer not null default 2 check (close_after_missed >= 1 and close_after_missed <= 10),
  incremental_stop_pages integer not null default 3 check (incremental_stop_pages >= 1 and incremental_stop_pages <= 50),
  max_pages_incremental  integer not null default 200 check (max_pages_incremental >= 1 and max_pages_incremental <= 100000),
  max_pages_full         integer not null default 20000 check (max_pages_full >= 1 and max_pages_full <= 100000),
  outputs                text[] not null default '{}'::text[],
  enabled                boolean not null default true,
  next_run_at            timestamptz,
  next_full_sweep_at     timestamptz,
  last_run_id            text check (char_length(last_run_id) <= 40),
  last_run_at            timestamptz,
  last_run_status        text check (char_length(last_run_status) <= 40),
  last_full_sweep_at     timestamptz,
  last_result            jsonb not null default '{}'::jsonb,
  total_jobs             integer not null default 0 check (total_jobs >= 0)
);

create index job_source_monitors_by_ws_created on careercloud.job_source_monitors (workspace_id, created_at desc, id desc);
create index job_source_monitors_by_ws_source_name on careercloud.job_source_monitors (workspace_id, source_name);
create index job_source_monitors_by_ws_source_type on careercloud.job_source_monitors (workspace_id, source_type);
create index job_source_monitors_by_ws_strategy on careercloud.job_source_monitors (workspace_id, strategy);
create index job_source_monitors_by_ws_schedule on careercloud.job_source_monitors (workspace_id, schedule);
create index job_source_monitors_by_ws_next_run_at on careercloud.job_source_monitors (workspace_id, next_run_at);
create unique index job_source_monitors_uq_name on careercloud.job_source_monitors (workspace_id, name);
create trigger job_source_monitors_guard before update on careercloud.job_source_monitors
  for each row execute function careercloud.guard_platform_row();
alter table careercloud.job_source_monitors enable row level security;
create policy job_source_monitors_select on careercloud.job_source_monitors for select to authenticated
  using (careercloud.is_member(workspace_id));
create policy job_source_monitors_insert on careercloud.job_source_monitors for insert to authenticated
  with check (careercloud.can_write(workspace_id) and created_by = auth.uid());
create policy job_source_monitors_update on careercloud.job_source_monitors for update to authenticated
  using (careercloud.can_write(workspace_id)) with check (careercloud.can_write(workspace_id));
create policy job_source_monitors_delete on careercloud.job_source_monitors for delete to authenticated
  using (careercloud.can_write(workspace_id));
grant select, insert, update, delete on careercloud.job_source_monitors to authenticated;

-- ---------------------------------------------------------------------------
-- One execution of a job source monitor (incremental or full sweep) with its counts and a resumable checkpoint.
create table careercloud.job_monitor_runs (
  id                     text primary key check (id ~ '^jmr_[0-9a-f]{32}$'),
  workspace_id           uuid not null references careercloud.workspaces (id) on delete cascade,
  created_at             timestamptz not null default now(),
  updated_at             timestamptz not null default now(),
  created_by             uuid,
  version                integer not null default 1,
  monitor_id             text not null check (char_length(monitor_id) <= 40),
  mode                   text not null default 'incremental' check (mode in ('incremental', 'full')),
  trigger                text not null default 'schedule' check (trigger in ('schedule', 'manual', 'api')),
  status                 text not null default 'queued' check (status in ('queued', 'running', 'completed', 'partial', 'failed', 'cancelled')),
  task_id                text check (char_length(task_id) <= 40),
  started_at             timestamptz,
  finished_at            timestamptz,
  pages                  integer not null default 0 check (pages >= 0),
  found                  integer not null default 0 check (found >= 0),
  new_count              integer not null default 0 check (new_count >= 0),
  changed_count          integer not null default 0 check (changed_count >= 0),
  unchanged_count        integer not null default 0 check (unchanged_count >= 0),
  reopened_count         integer not null default 0 check (reopened_count >= 0),
  closed_count           integer not null default 0 check (closed_count >= 0),
  rejected_count         integer not null default 0 check (rejected_count >= 0),
  error_count            integer not null default 0 check (error_count >= 0),
  warning_count          integer not null default 0 check (warning_count >= 0),
  request_count          integer not null default 0 check (request_count >= 0),
  duration_seconds       double precision check (duration_seconds >= 0),
  stop_reason            text check (char_length(stop_reason) <= 500),
  error                  text check (char_length(error) <= 2000),
  checkpoint             jsonb not null default '{}'::jsonb,
  notes                  jsonb not null default '[]'::jsonb
);

create index job_monitor_runs_by_ws_created on careercloud.job_monitor_runs (workspace_id, created_at desc, id desc);
create index job_monitor_runs_by_ws_monitor_id on careercloud.job_monitor_runs (workspace_id, monitor_id);
create index job_monitor_runs_by_ws_mode on careercloud.job_monitor_runs (workspace_id, mode);
create index job_monitor_runs_by_ws_trigger on careercloud.job_monitor_runs (workspace_id, trigger);
create index job_monitor_runs_by_ws_status on careercloud.job_monitor_runs (workspace_id, status);
create trigger job_monitor_runs_guard before update on careercloud.job_monitor_runs
  for each row execute function careercloud.guard_platform_row();
alter table careercloud.job_monitor_runs enable row level security;
create policy job_monitor_runs_select on careercloud.job_monitor_runs for select to authenticated
  using (careercloud.is_member(workspace_id));
create policy job_monitor_runs_insert on careercloud.job_monitor_runs for insert to authenticated
  with check (careercloud.can_write(workspace_id) and created_by = auth.uid());
create policy job_monitor_runs_update on careercloud.job_monitor_runs for update to authenticated
  using (careercloud.can_write(workspace_id)) with check (careercloud.can_write(workspace_id));
create policy job_monitor_runs_delete on careercloud.job_monitor_runs for delete to authenticated
  using (careercloud.can_write(workspace_id));
grant select, insert, update, delete on careercloud.job_monitor_runs to authenticated;

-- ---------------------------------------------------------------------------
-- Job history: when a posting appeared, which fields changed (previous values kept), when it closed or reopened.
create table careercloud.job_posting_changes (
  id                     text primary key check (id ~ '^jpc_[0-9a-f]{32}$'),
  workspace_id           uuid not null references careercloud.workspaces (id) on delete cascade,
  created_at             timestamptz not null default now(),
  updated_at             timestamptz not null default now(),
  created_by             uuid,
  version                integer not null default 1,
  job_posting_id         text not null check (char_length(job_posting_id) <= 40),
  monitor_id             text check (char_length(monitor_id) <= 40),
  run_id                 text check (char_length(run_id) <= 40),
  import_id              text check (char_length(import_id) <= 40),
  change                 text not null default 'new' check (change in ('new', 'changed', 'closed', 'reopened')),
  changed_fields         text[] not null default '{}'::text[],
  before                 jsonb not null default '{}'::jsonb,
  after                  jsonb not null default '{}'::jsonb,
  detected_at            timestamptz not null
);

create index job_posting_changes_by_ws_created on careercloud.job_posting_changes (workspace_id, created_at desc, id desc);
create index job_posting_changes_by_ws_job_posting_id on careercloud.job_posting_changes (workspace_id, job_posting_id);
create index job_posting_changes_by_ws_monitor_id on careercloud.job_posting_changes (workspace_id, monitor_id);
create index job_posting_changes_by_ws_run_id on careercloud.job_posting_changes (workspace_id, run_id);
create index job_posting_changes_by_ws_change on careercloud.job_posting_changes (workspace_id, change);
create trigger job_posting_changes_guard before update on careercloud.job_posting_changes
  for each row execute function careercloud.guard_platform_row();
alter table careercloud.job_posting_changes enable row level security;
create policy job_posting_changes_select on careercloud.job_posting_changes for select to authenticated
  using (careercloud.is_member(workspace_id));
create policy job_posting_changes_insert on careercloud.job_posting_changes for insert to authenticated
  with check (careercloud.can_write(workspace_id) and created_by = auth.uid());
grant select, insert on careercloud.job_posting_changes to authenticated;

-- ---------------------------------------------------------------------------
-- A historical CSV/XLSX job file: detected headers, the confirmed column mapping, validation, and a resumable import into job_postings.
create table careercloud.job_imports (
  id                     text primary key check (id ~ '^jimp_[0-9a-f]{32}$'),
  workspace_id           uuid not null references careercloud.workspaces (id) on delete cascade,
  created_at             timestamptz not null default now(),
  updated_at             timestamptz not null default now(),
  created_by             uuid,
  version                integer not null default 1,
  filename               text not null check (char_length(filename) <= 300),
  format                 text not null default 'csv' check (format in ('csv', 'xlsx')),
  storage_key            text not null check (char_length(storage_key) <= 500),
  size_bytes             bigint not null default 0 check (size_bytes >= 0),
  sheet                  text check (char_length(sheet) <= 200),
  headers                text[] not null default '{}'::text[],
  row_count              integer not null default 0 check (row_count >= 0),
  mapping                jsonb not null default '{}'::jsonb,
  default_source         text check (char_length(default_source) <= 200),
  status                 text not null default 'uploaded' check (status in ('uploaded', 'validated', 'importing', 'completed', 'failed', 'cancelled')),
  task_id                text check (char_length(task_id) <= 40),
  validation             jsonb not null default '{}'::jsonb,
  stats                  jsonb not null default '{}'::jsonb,
  checkpoint             jsonb not null default '{}'::jsonb,
  error                  text check (char_length(error) <= 2000)
);

create index job_imports_by_ws_created on careercloud.job_imports (workspace_id, created_at desc, id desc);
create index job_imports_by_ws_format on careercloud.job_imports (workspace_id, format);
create index job_imports_by_ws_status on careercloud.job_imports (workspace_id, status);
create trigger job_imports_guard before update on careercloud.job_imports
  for each row execute function careercloud.guard_platform_row();
alter table careercloud.job_imports enable row level security;
create policy job_imports_select on careercloud.job_imports for select to authenticated
  using (careercloud.is_member(workspace_id));
create policy job_imports_insert on careercloud.job_imports for insert to authenticated
  with check (careercloud.can_write(workspace_id) and created_by = auth.uid());
create policy job_imports_update on careercloud.job_imports for update to authenticated
  using (careercloud.can_write(workspace_id)) with check (careercloud.can_write(workspace_id));
create policy job_imports_delete on careercloud.job_imports for delete to authenticated
  using (careercloud.can_write(workspace_id));
grant select, insert, update, delete on careercloud.job_imports to authenticated;

-- ---------------------------------------------------------------------------
-- A relevance keyword universe (e.g. IT_Crawler_Keywords.xlsx): keyword -> category, category groups, noise terms and HIGH/REVIEW thresholds; one active set per workspace.
create table careercloud.job_keyword_sets (
  id                     text primary key check (id ~ '^jks_[0-9a-f]{32}$'),
  workspace_id           uuid not null references careercloud.workspaces (id) on delete cascade,
  created_at             timestamptz not null default now(),
  updated_at             timestamptz not null default now(),
  created_by             uuid,
  version                integer not null default 1,
  name                   text not null check (char_length(name) <= 200),
  filename               text check (char_length(filename) <= 300),
  active                 boolean not null default false,
  keywords               jsonb not null default '[]'::jsonb,
  categories             jsonb not null default '[]'::jsonb,
  groups                 jsonb not null default '{}'::jsonb,
  negative_terms         jsonb not null default '[]'::jsonb,
  thresholds             jsonb not null default '{}'::jsonb,
  problems               jsonb not null default '[]'::jsonb,
  keyword_count          integer not null default 0 check (keyword_count >= 0)
);

create index job_keyword_sets_by_ws_created on careercloud.job_keyword_sets (workspace_id, created_at desc, id desc);
create index job_keyword_sets_by_ws_active on careercloud.job_keyword_sets (workspace_id, active);
create unique index job_keyword_sets_uq_name on careercloud.job_keyword_sets (workspace_id, name);
create trigger job_keyword_sets_guard before update on careercloud.job_keyword_sets
  for each row execute function careercloud.guard_platform_row();
alter table careercloud.job_keyword_sets enable row level security;
create policy job_keyword_sets_select on careercloud.job_keyword_sets for select to authenticated
  using (careercloud.is_member(workspace_id));
create policy job_keyword_sets_insert on careercloud.job_keyword_sets for insert to authenticated
  with check (careercloud.can_write(workspace_id) and created_by = auth.uid());
create policy job_keyword_sets_update on careercloud.job_keyword_sets for update to authenticated
  using (careercloud.can_write(workspace_id)) with check (careercloud.can_write(workspace_id));
create policy job_keyword_sets_delete on careercloud.job_keyword_sets for delete to authenticated
  using (careercloud.can_write(workspace_id));
grant select, insert, update, delete on careercloud.job_keyword_sets to authenticated;

-- ---------------------------------------------------------------------------
-- Job company names that did not match exactly one CRM company: reviewed by a person; CRM companies are never created automatically from jobs.
create table careercloud.job_company_reviews (
  id                     text primary key check (id ~ '^jcr_[0-9a-f]{32}$'),
  workspace_id           uuid not null references careercloud.workspaces (id) on delete cascade,
  created_at             timestamptz not null default now(),
  updated_at             timestamptz not null default now(),
  created_by             uuid,
  version                integer not null default 1,
  company_name           text not null check (char_length(company_name) <= 300),
  normalized_name        text not null check (char_length(normalized_name) <= 300),
  status                 text not null default 'pending' check (status in ('pending', 'linked', 'ignored')),
  reason                 text check (char_length(reason) <= 300),
  candidate_ids          text[] not null default '{}'::text[],
  company_id             text check (char_length(company_id) <= 40),
  job_count              integer not null default 0 check (job_count >= 0),
  last_seen_at           timestamptz
);

create index job_company_reviews_by_ws_created on careercloud.job_company_reviews (workspace_id, created_at desc, id desc);
create index job_company_reviews_by_ws_status on careercloud.job_company_reviews (workspace_id, status);
create unique index job_company_reviews_uq_normalized_name on careercloud.job_company_reviews (workspace_id, normalized_name);
create trigger job_company_reviews_guard before update on careercloud.job_company_reviews
  for each row execute function careercloud.guard_platform_row();
alter table careercloud.job_company_reviews enable row level security;
create policy job_company_reviews_select on careercloud.job_company_reviews for select to authenticated
  using (careercloud.is_member(workspace_id));
create policy job_company_reviews_insert on careercloud.job_company_reviews for insert to authenticated
  with check (careercloud.can_write(workspace_id) and created_by = auth.uid());
create policy job_company_reviews_update on careercloud.job_company_reviews for update to authenticated
  using (careercloud.can_write(workspace_id)) with check (careercloud.can_write(workspace_id));
create policy job_company_reviews_delete on careercloud.job_company_reviews for delete to authenticated
  using (careercloud.can_write(workspace_id));
grant select, insert, update, delete on careercloud.job_company_reviews to authenticated;

-- ---------------------------------------------------------------------------
-- Supabase's anonymous role gets nothing in this schema.
-- ---------------------------------------------------------------------------

do $anon$
begin
  if exists (select 1 from pg_roles where rolname = 'anon') then
    revoke all on all tables in schema careercloud from anon;
    revoke all on all functions in schema careercloud from anon;
  end if;
end
$anon$;
