-- GENERATED by `python -m cloud.intel.store.ddl --write` from cloud/intel/store/spec.py.
-- Do not edit by hand: change the specs and regenerate before this migration is
-- applied anywhere; after that, write a new migration.
--
-- job_postings read policy, same meaning, set-based: the caller's workspaces are
-- computed once per query instead of calling is_member() for every row (at
-- 300k+ jobs that per-row call was ~90% of every Jobs page query).

-- ---------------------------------------------------------------------------
-- The caller's workspaces, once per statement (security definer like member_role).
-- ---------------------------------------------------------------------------

create function careercloud.my_workspace_ids() returns setof uuid
  language sql stable security definer
  set search_path = careercloud, pg_temp
  as $fn$ select w.id from careercloud.workspaces w where careercloud.member_role(w.id) is not null $fn$;

grant execute on function careercloud.my_workspace_ids() to authenticated;

drop policy job_postings_select on careercloud.job_postings;
create policy job_postings_select on careercloud.job_postings for select to authenticated
  using (workspace_id in (select careercloud.my_workspace_ids()));

-- ---------------------------------------------------------------------------
-- Supabase's anonymous role gets nothing in this schema.
-- ---------------------------------------------------------------------------

do $anon$
begin
  if exists (select 1 from pg_roles where rolname = 'anon') then
    revoke all on all tables in schema careercloud from anon;
    revoke all on all functions in schema careercloud from anon;
  end if;
end
$anon$;
