-- GENERATED by `python -m cloud.intel.store.ddl --write` from cloud/intel/store/spec.py.
-- Do not edit by hand: change the specs and regenerate before this migration is
-- applied anywhere; after that, write a new migration.
--
-- Job lifecycle: STALE (active beyond the monitor's stale_after_days) and EXPIRED
-- (aged out of a source's visible listing window) next to CLOSED, with the dates
-- and evidence (listing date, closure reason, last direct URL check); monitor
-- lifecycle settings and the daily job_lifecycle task. Job-derived hiring signals
-- (cluster, stack migration, departure) that may name a non-CRM company, contact
-- snapshots from authorized providers, and signal outcomes linking a signal to the
-- prospect, campaign and result. Existing rows keep their values; nothing is dropped.

-- ---------------------------------------------------------------------------
-- job_postings.status: widened choices
alter table careercloud.job_postings drop constraint job_postings_status_check,
  add constraint job_postings_status_check check (status in ('open', 'closed', 'unknown', 'stale', 'expired'));
-- hiring_signals.signal_type: widened choices
alter table careercloud.hiring_signals drop constraint hiring_signals_signal_type_check,
  add constraint hiring_signals_signal_type_check check (signal_type in ('NEW_ROLE', 'MULTIPLE_RELEVANT_ROLES', 'HIRING_SPIKE', 'HIRING_VELOCITY', 'LONG_OPEN_ROLE', 'HARD_TO_FILL', 'SPECIALIZED_TECHNOLOGY', 'PROJECT_IMPLEMENTATION', 'EXPANSION_HIRING', 'BACKFILL_REPLACEMENT', 'LEADERSHIP_HIRING', 'HIRING_CLUSTER', 'STACK_MIGRATION', 'DEPARTURE'));
-- platform_tasks.kind: widened choices
alter table careercloud.platform_tasks drop constraint platform_tasks_kind_check,
  add constraint platform_tasks_kind_check check (kind in ('crawl', 'discovery', 'scraper', 'enrichment', 'validation', 'research', 'analytics', 'workflow', 'import_merge', 'monitor', 'signals', 'export', 'source_search', 'email_validation_job', 'email_send', 'workflow_resume', 'scoring', 'internal_data', 'integration', 'job_monitor', 'job_import', 'job_lifecycle'));
-- job_posting_changes.change: widened choices
alter table careercloud.job_posting_changes drop constraint job_posting_changes_change_check,
  add constraint job_posting_changes_change_check check (change in ('new', 'changed', 'closed', 'reopened', 'stale', 'expired'));

-- ---------------------------------------------------------------------------
-- hiring_signals.company_id: no longer required
alter table careercloud.hiring_signals alter column company_id drop not null;

-- ---------------------------------------------------------------------------
alter table careercloud.job_postings add column listing_date           date;
create index job_postings_by_ws_listing_date on careercloud.job_postings (workspace_id, listing_date);
alter table careercloud.job_postings add column stale_at               timestamptz;
create index job_postings_by_ws_stale_at on careercloud.job_postings (workspace_id, stale_at);
alter table careercloud.job_postings add column expired_at             timestamptz;
create index job_postings_by_ws_expired_at on careercloud.job_postings (workspace_id, expired_at);
alter table careercloud.job_postings add column reopened_at            timestamptz;
alter table careercloud.job_postings add column closure_reason         text check (closure_reason in ('missed_full_sweeps', 'source_gone', 'manual'));
alter table careercloud.job_postings add column gone_checked_at        timestamptz;
alter table careercloud.job_postings add column gone_status            integer check (gone_status >= 0 and gone_status <= 999);
alter table careercloud.hiring_signals add column company_name           text check (char_length(company_name) <= 300);
create index hiring_signals_by_ws_company_name on careercloud.hiring_signals (workspace_id, company_name);
alter table careercloud.hiring_signals add column domain                 text check (char_length(domain) <= 255);
alter table careercloud.hiring_signals add column technologies           text[] not null default '{}'::text[];
alter table careercloud.hiring_signals add column contact_id             text check (char_length(contact_id) <= 40);
alter table careercloud.hiring_signals add column outcome                text check (outcome in ('contacted', 'replied', 'meeting', 'opportunity', 'no_response', 'disqualified'));
alter table careercloud.hiring_signals add column outcome_at             timestamptz;
alter table careercloud.hiring_signals add column outcome_counts         jsonb not null default '{}'::jsonb;
alter table careercloud.sequence_enrollments add column signal_id              text check (char_length(signal_id) <= 40);
create index sequence_enrollments_by_ws_signal_id on careercloud.sequence_enrollments (workspace_id, signal_id);
alter table careercloud.job_source_monitors add column stale_after_days       integer not null default 30 check (stale_after_days >= 1 and stale_after_days <= 365);
alter table careercloud.job_source_monitors add column visible_window_days    integer check (visible_window_days >= 1 and visible_window_days <= 3650);
alter table careercloud.job_source_monitors add column gone_checks_per_run    integer not null default 500 check (gone_checks_per_run >= 0 and gone_checks_per_run <= 20000);
alter table careercloud.job_source_monitors add column next_lifecycle_at      timestamptz;
create index job_source_monitors_by_ws_next_lifecycle_at on careercloud.job_source_monitors (workspace_id, next_lifecycle_at);
alter table careercloud.job_source_monitors add column last_lifecycle_at      timestamptz;
alter table careercloud.job_source_monitors add column last_lifecycle_result  jsonb not null default '{}'::jsonb;
alter table careercloud.job_monitor_runs add column expired_count          integer not null default 0 check (expired_count >= 0);
alter table careercloud.job_monitor_runs add column gone_checked_count     integer not null default 0 check (gone_checked_count >= 0);
alter table careercloud.job_monitor_runs add column gone_closed_count      integer not null default 0 check (gone_closed_count >= 0);

-- ---------------------------------------------------------------------------
-- What an authorized contact provider reported about a person on each refresh (company, title, employment status as the provider states it): the evidence behind DEPARTURE signals.
create table careercloud.contact_snapshots (
  id                     text primary key check (id ~ '^csn_[0-9a-f]{32}$'),
  workspace_id           uuid not null references careercloud.workspaces (id) on delete cascade,
  created_at             timestamptz not null default now(),
  updated_at             timestamptz not null default now(),
  created_by             uuid,
  version                integer not null default 1,
  contact_id             text not null check (char_length(contact_id) <= 40),
  provider               text not null default 'zoominfo' check (provider in ('zoominfo', 'seamless', 'manual')),
  provider_contact_id    text check (char_length(provider_contact_id) <= 200),
  company_id             text check (char_length(company_id) <= 40),
  company_name           text check (char_length(company_name) <= 300),
  title                  text check (char_length(title) <= 300),
  employment_status      text not null default 'unknown' check (employment_status in ('current', 'left_company', 'unknown')),
  observed_at            timestamptz not null,
  evidence               jsonb not null default '{}'::jsonb
);

create index contact_snapshots_by_ws_created on careercloud.contact_snapshots (workspace_id, created_at desc, id desc);
create index contact_snapshots_by_ws_contact_id on careercloud.contact_snapshots (workspace_id, contact_id);
create index contact_snapshots_by_ws_provider on careercloud.contact_snapshots (workspace_id, provider);
create index contact_snapshots_by_ws_provider_contact_id on careercloud.contact_snapshots (workspace_id, provider_contact_id);
create index contact_snapshots_by_ws_employment_status on careercloud.contact_snapshots (workspace_id, employment_status);
create trigger contact_snapshots_guard before update on careercloud.contact_snapshots
  for each row execute function careercloud.guard_platform_row();
alter table careercloud.contact_snapshots enable row level security;
create policy contact_snapshots_select on careercloud.contact_snapshots for select to authenticated
  using (careercloud.is_member(workspace_id));
create policy contact_snapshots_insert on careercloud.contact_snapshots for insert to authenticated
  with check (careercloud.can_write(workspace_id) and created_by = auth.uid());
grant select, insert on careercloud.contact_snapshots to authenticated;

-- ---------------------------------------------------------------------------
-- Closed loop: what happened after a signal produced a prospect/campaign (contacted, replied, meeting, opportunity, no response, disqualified), linked to the signal, company, prospect and campaign.
create table careercloud.signal_outcomes (
  id                     text primary key check (id ~ '^so_[0-9a-f]{32}$'),
  workspace_id           uuid not null references careercloud.workspaces (id) on delete cascade,
  created_at             timestamptz not null default now(),
  updated_at             timestamptz not null default now(),
  created_by             uuid,
  version                integer not null default 1,
  signal_id              text not null check (char_length(signal_id) <= 40),
  company_id             text check (char_length(company_id) <= 40),
  contact_id             text check (char_length(contact_id) <= 40),
  campaign_id            text check (char_length(campaign_id) <= 40),
  enrollment_id          text check (char_length(enrollment_id) <= 40),
  opportunity_id         text check (char_length(opportunity_id) <= 40),
  outcome                text not null default 'contacted' check (outcome in ('contacted', 'replied', 'meeting', 'opportunity', 'no_response', 'disqualified')),
  occurred_at            timestamptz not null,
  source                 text not null default 'message_event' check (source in ('message_event', 'enrollment', 'opportunity', 'manual')),
  note                   text check (char_length(note) <= 2000),
  data                   jsonb not null default '{}'::jsonb
);

create index signal_outcomes_by_ws_created on careercloud.signal_outcomes (workspace_id, created_at desc, id desc);
create index signal_outcomes_by_ws_signal_id on careercloud.signal_outcomes (workspace_id, signal_id);
create index signal_outcomes_by_ws_company_id on careercloud.signal_outcomes (workspace_id, company_id);
create index signal_outcomes_by_ws_contact_id on careercloud.signal_outcomes (workspace_id, contact_id);
create index signal_outcomes_by_ws_campaign_id on careercloud.signal_outcomes (workspace_id, campaign_id);
create index signal_outcomes_by_ws_enrollment_id on careercloud.signal_outcomes (workspace_id, enrollment_id);
create index signal_outcomes_by_ws_outcome on careercloud.signal_outcomes (workspace_id, outcome);
create index signal_outcomes_by_ws_source on careercloud.signal_outcomes (workspace_id, source);
create trigger signal_outcomes_guard before update on careercloud.signal_outcomes
  for each row execute function careercloud.guard_platform_row();
alter table careercloud.signal_outcomes enable row level security;
create policy signal_outcomes_select on careercloud.signal_outcomes for select to authenticated
  using (careercloud.is_member(workspace_id));
create policy signal_outcomes_insert on careercloud.signal_outcomes for insert to authenticated
  with check (careercloud.can_write(workspace_id) and created_by = auth.uid());
grant select, insert on careercloud.signal_outcomes to authenticated;

-- ---------------------------------------------------------------------------
-- Supabase's anonymous role gets nothing in this schema.
-- ---------------------------------------------------------------------------

do $anon$
begin
  if exists (select 1 from pg_roles where rolname = 'anon') then
    revoke all on all tables in schema careercloud from anon;
    revoke all on all functions in schema careercloud from anon;
  end if;
end
$anon$;
