-- GENERATED by `python -m cloud.intel.store.ddl --write` from cloud/intel/store/spec.py.
-- Do not edit by hand: change the specs and regenerate before this migration is
-- applied anywhere; after that, write a new migration.
--
-- Job CSV import/export at scale: background job exports with a "running" status,
-- progress, scope and a duplicate guard (the job_export task kind), and the import
-- that last touched each job posting (in-file duplicates across batches). Additive.

-- ---------------------------------------------------------------------------
-- platform_tasks.kind: widened choices
alter table careercloud.platform_tasks drop constraint platform_tasks_kind_check,
  add constraint platform_tasks_kind_check check (kind in ('crawl', 'discovery', 'scraper', 'enrichment', 'validation', 'research', 'analytics', 'workflow', 'import_merge', 'monitor', 'signals', 'export', 'source_search', 'email_validation_job', 'email_send', 'workflow_resume', 'scoring', 'internal_data', 'integration', 'job_monitor', 'job_import', 'job_lifecycle', 'job_export'));
-- exports.status: widened choices
alter table careercloud.exports drop constraint exports_status_check,
  add constraint exports_status_check check (status in ('queued', 'completed', 'failed', 'running'));

-- ---------------------------------------------------------------------------
alter table careercloud.job_postings add column last_import_id         text check (char_length(last_import_id) <= 40);
create index job_postings_by_ws_last_import_id on careercloud.job_postings (workspace_id, last_import_id);
alter table careercloud.exports add column scope                  text check (char_length(scope) <= 20);
alter table careercloud.exports add column total_rows             integer check (total_rows >= 0);
alter table careercloud.exports add column progress_rows          integer not null default 0 check (progress_rows >= 0);
alter table careercloud.exports add column task_id                text check (char_length(task_id) <= 40);
alter table careercloud.exports add column dedupe_key             text check (char_length(dedupe_key) <= 64);
create index exports_by_ws_dedupe_key on careercloud.exports (workspace_id, dedupe_key);
alter table careercloud.exports add column finished_at            timestamptz;

-- ---------------------------------------------------------------------------
-- Supabase's anonymous role gets nothing in this schema.
-- ---------------------------------------------------------------------------

do $anon$
begin
  if exists (select 1 from pg_roles where rolname = 'anon') then
    revoke all on all tables in schema careercloud from anon;
    revoke all on all functions in schema careercloud from anon;
  end if;
end
$anon$;
