"""Generate the platform migration from :mod:`cloud.intel.store.spec`.

    python -m cloud.intel.store.ddl            # print the SQL
    python -m cloud.intel.store.ddl --write    # (re)write cloud/db/migrations/0003_platform.sql

The migration is generated once and committed; ``test_platform_ddl`` fails if
the committed file drifts from the specs. Because applied migrations are
checksummed, a schema change after deployment is a *new* migration, never an
edit of this one.

Security model (PostgreSQL row-level security, same approach as 0001):

* ``careercloud.workspaces`` and ``careercloud.workspace_members`` hold tenancy.
* ``careercloud.member_role(ws)`` returns the caller's role in a workspace from
  ``auth.uid()``; it is ``security definer`` so policies can call it without
  recursing into the members table's own policy.
* Every platform table: members SELECT; writers (owner/admin/member) INSERT,
  UPDATE, DELETE; viewers read only. ``append_only`` tables grant no UPDATE or
  DELETE; ``system_write`` tables grant users SELECT only — the worker, which
  connects as the table owner, writes them.
* A trigger makes ``id``, ``workspace_id``, ``created_at`` and ``created_by``
  immutable for every role and bumps ``version``/``updated_at`` on each update.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import List

from cloud.intel.store.spec import COMMON_COLUMNS, ENTITIES, PG_TYPES, Col, EntitySpec

MIGRATION = Path(__file__).resolve().parents[2] / "db" / "migrations" / "0003_platform.sql"

_HEADER = """\
-- GENERATED by `python -m cloud.intel.store.ddl --write` from cloud/intel/store/spec.py.
-- Do not edit by hand: change the specs and regenerate before this migration is
-- applied anywhere; after that, write a new migration.
--
-- CareerCrawler platform: workspaces, CRM, company/job/hiring intelligence,
-- providers and credits, email validation, scraping, GTM, automation, research,
-- monitoring, tasks and audit. Everything is workspace-scoped with RLS.

-- ---------------------------------------------------------------------------
-- Tenancy
-- ---------------------------------------------------------------------------

create table careercloud.workspaces (
  id                   uuid primary key default gen_random_uuid(),
  name                 text not null check (char_length(name) between 1 and 200),
  slug                 text not null unique check (slug ~ '^[a-z0-9][a-z0-9-]{1,62}$'),
  created_by           uuid not null,
  created_at           timestamptz not null default now(),
  updated_at           timestamptz not null default now(),
  -- May private data from this workspace be sent to external AI providers?
  ai_external_allowed  boolean not null default false,
  settings             jsonb not null default '{}'::jsonb
);

create table careercloud.workspace_members (
  workspace_id  uuid not null references careercloud.workspaces (id) on delete cascade,
  user_id       uuid not null,
  role          text not null check (role in ('owner', 'admin', 'member', 'viewer')),
  created_at    timestamptz not null default now(),
  primary key (workspace_id, user_id)
);

create index workspace_members_by_user on careercloud.workspace_members (user_id);

create function careercloud.member_role(ws uuid) returns text
  language sql stable security definer
  set search_path = careercloud, pg_temp
  as $fn$
    select m.role from careercloud.workspace_members m
    where m.workspace_id = ws and m.user_id = auth.uid()
  $fn$;

create function careercloud.is_member(ws uuid) returns boolean
  language sql stable
  as $fn$ select careercloud.member_role(ws) is not null $fn$;

create function careercloud.can_write(ws uuid) returns boolean
  language sql stable
  as $fn$ select coalesce(careercloud.member_role(ws) in ('owner', 'admin', 'member'), false) $fn$;

create function careercloud.can_admin(ws uuid) returns boolean
  language sql stable
  as $fn$ select coalesce(careercloud.member_role(ws) in ('owner', 'admin'), false) $fn$;

-- Creating a workspace also makes the caller its owner, atomically. Users
-- cannot insert into workspace_members directly for a workspace they do not
-- administer, so this is the only way to bootstrap one.
create function careercloud.create_workspace(p_name text, p_slug text) returns uuid
  language plpgsql security definer
  set search_path = careercloud, pg_temp
  as $fn$
declare
  me uuid := auth.uid();
  ws uuid;
begin
  if me is null then
    raise exception 'sign in required' using errcode = 'insufficient_privilege';
  end if;
  insert into careercloud.workspaces (name, slug, created_by) values (p_name, p_slug, me) returning id into ws;
  insert into careercloud.workspace_members (workspace_id, user_id, role) values (ws, me, 'owner');
  return ws;
end
$fn$;

grant execute on function careercloud.member_role(uuid) to authenticated;
grant execute on function careercloud.is_member(uuid) to authenticated;
grant execute on function careercloud.can_write(uuid) to authenticated;
grant execute on function careercloud.can_admin(uuid) to authenticated;
grant execute on function careercloud.create_workspace(text, text) to authenticated;

alter table careercloud.workspaces enable row level security;
alter table careercloud.workspace_members enable row level security;

create policy workspaces_select on careercloud.workspaces
  for select to authenticated using (careercloud.is_member(id));
create policy workspaces_update on careercloud.workspaces
  for update to authenticated using (careercloud.can_admin(id)) with check (careercloud.can_admin(id));

create policy members_select on careercloud.workspace_members
  for select to authenticated using (careercloud.is_member(workspace_id));
create policy members_insert on careercloud.workspace_members
  for insert to authenticated with check (careercloud.can_admin(workspace_id) and role <> 'owner');
create policy members_update on careercloud.workspace_members
  for update to authenticated using (careercloud.can_admin(workspace_id))
  with check (careercloud.can_admin(workspace_id) and role <> 'owner');
create policy members_delete on careercloud.workspace_members
  for delete to authenticated using (careercloud.can_admin(workspace_id) and role <> 'owner');

grant select on careercloud.workspaces to authenticated;
grant update (name, settings, ai_external_allowed, updated_at) on careercloud.workspaces to authenticated;
grant select, insert, update, delete on careercloud.workspace_members to authenticated;

-- Shared by every platform table: identity is immutable, versions increase.
create function careercloud.guard_platform_row() returns trigger
  language plpgsql
  as $fn$
begin
  if new.id <> old.id or new.workspace_id <> old.workspace_id or new.created_at <> old.created_at
     or new.created_by is distinct from old.created_by then
    raise exception 'row identity, workspace and creation are immutable'
      using errcode = 'check_violation';
  end if;
  new.version := old.version + 1;
  new.updated_at := now();
  return new;
end
$fn$;
"""

_FOOTER = """
-- ---------------------------------------------------------------------------
-- Supabase's anonymous role gets nothing in this schema.
-- ---------------------------------------------------------------------------

do $anon$
begin
  if exists (select 1 from pg_roles where rolname = 'anon') then
    revoke all on all tables in schema careercloud from anon;
    revoke all on all functions in schema careercloud from anon;
  end if;
end
$anon$;
"""


def _literal(value) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return repr(value)
    if isinstance(value, (dict, list)):
        import json

        if isinstance(value, list) and not value:
            return "'[]'::jsonb"
        return "'" + json.dumps(value, sort_keys=True).replace("'", "''") + "'::jsonb"
    return "'" + str(value).replace("'", "''") + "'"


def _column_sql(name: str, col: Col, spec: EntitySpec) -> str:
    pg = PG_TYPES[col.kind]
    parts = [f"{name:<22} {pg}"]
    if name == "id":
        parts = [f"{'id':<22} text primary key check (id ~ '^{spec.prefix}_[0-9a-f]{{32}}$')"]
        return " ".join(parts)
    if name == "workspace_id":
        return f"{'workspace_id':<22} uuid not null references careercloud.workspaces (id) on delete cascade"
    if col.required:
        parts.append("not null")
    if col.default is not None:
        if col.kind == "tags":
            parts.append("default '{}'::text[]")
        else:
            parts.append(f"default {_literal(col.default)}")
    elif name in ("created_at", "updated_at"):
        parts.append("default now()")
    checks: List[str] = []
    if col.max_len is not None and col.kind == "text":
        checks.append(f"char_length({name}) <= {col.max_len}")
    if col.choices:
        options = ", ".join(_literal(c) for c in col.choices)
        checks.append(f"{name} in ({options})")
    if col.minimum is not None:
        checks.append(f"{name} >= {col.minimum:g}")
    if col.maximum is not None:
        checks.append(f"{name} <= {col.maximum:g}")
    if checks:
        parts.append("check (" + " and ".join(checks) + ")")
    return " ".join(parts)


def table_sql(spec: EntitySpec) -> str:
    t = f"careercloud.{spec.table}"
    columns = {**COMMON_COLUMNS, **spec.columns}
    lines = [f"create table {t} ("]
    body = [f"  {_column_sql(name, col, spec)}" for name, col in columns.items()]
    lines.append(",\n".join(body))
    lines.append(");")
    out = ["-- " + (spec.description or spec.name), "\n".join(lines), ""]

    out.append(f"create index {spec.table}_by_ws_created on {t} (workspace_id, created_at desc, id desc);")
    for name, col in spec.columns.items():
        if col.index:
            out.append(f"create index {spec.table}_by_ws_{name} on {t} (workspace_id, {name});")
    for group in spec.unique:
        cols = ", ".join(group)
        nullable = [c for c in group if not spec.columns[c].required]
        where = ""
        if nullable:
            where = " where " + " and ".join(f"{c} is not null" for c in nullable)
        out.append(f"create unique index {spec.table}_uq_{'_'.join(group)} on {t} (workspace_id, {cols}){where};")

    out.append(f"create trigger {spec.table}_guard before update on {t}")
    out.append("  for each row execute function careercloud.guard_platform_row();")
    out.append(f"alter table {t} enable row level security;")
    out.append(f"create policy {spec.table}_select on {t} for select to authenticated")
    out.append("  using (careercloud.is_member(workspace_id));")
    grants = ["select"]
    if not spec.system_write:
        out.append(f"create policy {spec.table}_insert on {t} for insert to authenticated")
        out.append("  with check (careercloud.can_write(workspace_id) and created_by = auth.uid());")
        grants.append("insert")
        if not spec.append_only:
            out.append(f"create policy {spec.table}_update on {t} for update to authenticated")
            out.append("  using (careercloud.can_write(workspace_id)) with check (careercloud.can_write(workspace_id));")
            out.append(f"create policy {spec.table}_delete on {t} for delete to authenticated")
            out.append("  using (careercloud.can_write(workspace_id));")
            grants += ["update", "delete"]
    out.append(f"grant {', '.join(grants)} on {t} to authenticated;")
    return "\n".join(out) + "\n"


def generate() -> str:
    parts = [_HEADER]
    for spec in ENTITIES.values():
        parts.append("\n-- ---------------------------------------------------------------------------\n")
        parts.append(table_sql(spec))
    parts.append(_FOOTER)
    return "".join(parts)


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--write", action="store_true")
    args = parser.parse_args(argv)
    sql = generate()
    if args.write:
        MIGRATION.write_text(sql, encoding="utf-8", newline="\n")
        print(f"wrote {MIGRATION} ({len(sql)} bytes, {len(ENTITIES)} tables)")
    else:
        sys.stdout.write(sql)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
