"""Generate the platform migration from :mod:`cloud.intel.store.spec`.

    python -m cloud.intel.store.ddl            # print the SQL
    python -m cloud.intel.store.ddl --write    # (re)write cloud/db/migrations/0003_platform.sql

The migration is generated once and committed; ``test_platform_ddl`` fails if
the committed file drifts from the specs. Because applied migrations are
checksummed, a schema change after deployment is a *new* migration, never an
edit of this one.

Security model (PostgreSQL row-level security, same approach as 0001):

* ``careercloud.workspaces`` and ``careercloud.workspace_members`` hold tenancy.
* ``careercloud.member_role(ws)`` returns the caller's role in a workspace from
  ``auth.uid()``; it is ``security definer`` so policies can call it without
  recursing into the members table's own policy.
* Every platform table: members SELECT; writers (owner/admin/member) INSERT,
  UPDATE, DELETE; viewers read only. ``append_only`` tables grant no UPDATE or
  DELETE; ``system_write`` tables grant users SELECT only — the worker, which
  connects as the table owner, writes them.
* A trigger makes ``id``, ``workspace_id``, ``created_at`` and ``created_by``
  immutable for every role and bumps ``version``/``updated_at`` on each update.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import List, Optional, Tuple

from cloud.intel.store.spec import COMMON_COLUMNS, ENTITIES, PG_TYPES, Col, EntitySpec

MIGRATIONS_DIR = Path(__file__).resolve().parents[2] / "db" / "migrations"
MIGRATION = MIGRATIONS_DIR / "0003_platform.sql"
#: version -> file. 0003 holds tenancy and the original entities; later versions
#: only add tables (applied migrations are never edited).
GENERATED = {"0003": MIGRATION, "0004": MIGRATIONS_DIR / "0004_ai_control_room.sql",
             "0005": MIGRATIONS_DIR / "0005_ai_usage.sql", "0006": MIGRATIONS_DIR / "0006_scraper_v4.sql",
             "0007": MIGRATIONS_DIR / "0007_sana_gtm_completion.sql",
             "0008": MIGRATIONS_DIR / "0008_email_evidence_cache.sql",
             "0009": MIGRATIONS_DIR / "0009_user_invitations.sql"}

_HEADER_0009 = """-- GENERATED by `python -m cloud.intel.store.ddl --write` from cloud/intel/store/spec.py.
-- Do not edit by hand: change the specs and regenerate before this migration is
-- applied anywhere; after that, write a new migration.
--
-- User invitations: invitee name, team to join, inviter label and delivery
-- bookkeeping on workspace_invitations, and its RLS narrowed to workspace admins
-- (owner/admin), because the rows hold invitee emails and token hashes. The
-- invitation token itself is never stored.
"""

_HEADER_0008 = """-- GENERATED by `python -m cloud.intel.store.ddl --write` from cloud/intel/store/spec.py.
-- Do not edit by hand: change the specs and regenerate before this migration is
-- applied anywhere; after that, write a new migration.
--
-- Email validation evidence cache: DNS/MX, SPF/DMARC, SMTP preflight, public-web
-- evidence and catch-all results keyed by a SHA-256 of the address, domain or host
-- (never the plain address), each with its own expiry. Same tenancy and RLS model as 0003.
"""

_HEADER_0007 = """-- GENERATED by `python -m cloud.intel.store.ddl --write` from cloud/intel/store/spec.py.
-- Do not edit by hand: change the specs and regenerate before this migration is
-- applied anywhere; after that, write a new migration.
--
-- SANA GTM completion: email validation jobs, connected mailboxes and the
-- outbound queue, normalized provider events, scoped suppression, teams,
-- invitations and the manager role, notifications, saved reports, explainable
-- score snapshots, integration deliveries, workflow graphs/approvals, and
-- internal-data schema comparison. Same tenancy and RLS model as 0003.
"""

#: Hand-written SQL appended to 0007: the tenancy objects are not entity specs.
_EXTRA_0007 = """
-- ---------------------------------------------------------------------------
-- Tenancy: the manager role (writes like a member, manages teams/assignment).
-- ---------------------------------------------------------------------------

alter table careercloud.workspace_members drop constraint workspace_members_role_check,
  add constraint workspace_members_role_check check (role in ('owner', 'admin', 'manager', 'member', 'viewer'));

create or replace function careercloud.can_write(ws uuid) returns boolean
  language sql stable
  as $fn$ select coalesce(careercloud.member_role(ws) in ('owner', 'admin', 'manager', 'member'), false) $fn$;
"""

_HEADER_0006 = """-- GENERATED by `python -m cloud.intel.store.ddl --write` from cloud/intel/store/spec.py.
-- Do not edit by hand: change the specs and regenerate before this migration is
-- applied anywhere; after that, write a new migration.
--
-- AI scraper V2-V4: every page a run visited, saved templates, CRM proposals
-- (applied only after review), and the fine-grained scraper run states.
-- Same tenancy and RLS model as 0003.
"""

_HEADER_0005 = """-- GENERATED by `python -m cloud.intel.store.ddl --write` from cloud/intel/store/spec.py.
-- Do not edit by hand: change the specs and regenerate before this migration is
-- applied anywhere; after that, write a new migration.
--
-- Real AI providers: per-call usage (provider, model, tokens, estimated cost,
-- request id) for budgets and cost reporting. Same tenancy and RLS model as 0003.
"""

_HEADER_0004 = """-- GENERATED by `python -m cloud.intel.store.ddl --write` from cloud/intel/store/spec.py.
-- Do not edit by hand: change the specs and regenerate before this migration is
-- applied anywhere; after that, write a new migration.
--
-- AI Control Room: agent sessions, messages, runs, tool-call steps, approvals,
-- results, workspace AI memory, proactive insights and saved requests/views.
-- Same tenancy and RLS model as 0003 (workspace membership via member_role()).
"""

_HEADER = """\
-- GENERATED by `python -m cloud.intel.store.ddl --write` from cloud/intel/store/spec.py.
-- Do not edit by hand: change the specs and regenerate before this migration is
-- applied anywhere; after that, write a new migration.
--
-- CareerCrawler platform: workspaces, CRM, company/job/hiring intelligence,
-- providers and credits, email validation, scraping, GTM, automation, research,
-- monitoring, tasks and audit. Everything is workspace-scoped with RLS.

-- ---------------------------------------------------------------------------
-- Tenancy
-- ---------------------------------------------------------------------------

create table careercloud.workspaces (
  id                   uuid primary key default gen_random_uuid(),
  name                 text not null check (char_length(name) between 1 and 200),
  slug                 text not null unique check (slug ~ '^[a-z0-9][a-z0-9-]{1,62}$'),
  created_by           uuid not null,
  created_at           timestamptz not null default now(),
  updated_at           timestamptz not null default now(),
  -- May private data from this workspace be sent to external AI providers?
  ai_external_allowed  boolean not null default false,
  settings             jsonb not null default '{}'::jsonb
);

create table careercloud.workspace_members (
  workspace_id  uuid not null references careercloud.workspaces (id) on delete cascade,
  user_id       uuid not null,
  role          text not null check (role in ('owner', 'admin', 'member', 'viewer')),
  created_at    timestamptz not null default now(),
  primary key (workspace_id, user_id)
);

create index workspace_members_by_user on careercloud.workspace_members (user_id);

create function careercloud.member_role(ws uuid) returns text
  language sql stable security definer
  set search_path = careercloud, pg_temp
  as $fn$
    select m.role from careercloud.workspace_members m
    where m.workspace_id = ws and m.user_id = auth.uid()
  $fn$;

create function careercloud.is_member(ws uuid) returns boolean
  language sql stable
  as $fn$ select careercloud.member_role(ws) is not null $fn$;

create function careercloud.can_write(ws uuid) returns boolean
  language sql stable
  as $fn$ select coalesce(careercloud.member_role(ws) in ('owner', 'admin', 'member'), false) $fn$;

create function careercloud.can_admin(ws uuid) returns boolean
  language sql stable
  as $fn$ select coalesce(careercloud.member_role(ws) in ('owner', 'admin'), false) $fn$;

-- Creating a workspace also makes the caller its owner, atomically. Users
-- cannot insert into workspace_members directly for a workspace they do not
-- administer, so this is the only way to bootstrap one.
create function careercloud.create_workspace(p_name text, p_slug text) returns uuid
  language plpgsql security definer
  set search_path = careercloud, pg_temp
  as $fn$
declare
  me uuid := auth.uid();
  ws uuid;
begin
  if me is null then
    raise exception 'sign in required' using errcode = 'insufficient_privilege';
  end if;
  insert into careercloud.workspaces (name, slug, created_by) values (p_name, p_slug, me) returning id into ws;
  insert into careercloud.workspace_members (workspace_id, user_id, role) values (ws, me, 'owner');
  return ws;
end
$fn$;

grant execute on function careercloud.member_role(uuid) to authenticated;
grant execute on function careercloud.is_member(uuid) to authenticated;
grant execute on function careercloud.can_write(uuid) to authenticated;
grant execute on function careercloud.can_admin(uuid) to authenticated;
grant execute on function careercloud.create_workspace(text, text) to authenticated;

alter table careercloud.workspaces enable row level security;
alter table careercloud.workspace_members enable row level security;

create policy workspaces_select on careercloud.workspaces
  for select to authenticated using (careercloud.is_member(id));
create policy workspaces_update on careercloud.workspaces
  for update to authenticated using (careercloud.can_admin(id)) with check (careercloud.can_admin(id));

create policy members_select on careercloud.workspace_members
  for select to authenticated using (careercloud.is_member(workspace_id));
create policy members_insert on careercloud.workspace_members
  for insert to authenticated with check (careercloud.can_admin(workspace_id) and role <> 'owner');
create policy members_update on careercloud.workspace_members
  for update to authenticated using (careercloud.can_admin(workspace_id))
  with check (careercloud.can_admin(workspace_id) and role <> 'owner');
create policy members_delete on careercloud.workspace_members
  for delete to authenticated using (careercloud.can_admin(workspace_id) and role <> 'owner');

grant select on careercloud.workspaces to authenticated;
grant update (name, settings, ai_external_allowed, updated_at) on careercloud.workspaces to authenticated;
grant select, insert, update, delete on careercloud.workspace_members to authenticated;

-- Shared by every platform table: identity is immutable, versions increase.
create function careercloud.guard_platform_row() returns trigger
  language plpgsql
  as $fn$
begin
  if new.id <> old.id or new.workspace_id <> old.workspace_id or new.created_at <> old.created_at
     or new.created_by is distinct from old.created_by then
    raise exception 'row identity, workspace and creation are immutable'
      using errcode = 'check_violation';
  end if;
  new.version := old.version + 1;
  new.updated_at := now();
  return new;
end
$fn$;
"""

_FOOTER = """
-- ---------------------------------------------------------------------------
-- Supabase's anonymous role gets nothing in this schema.
-- ---------------------------------------------------------------------------

do $anon$
begin
  if exists (select 1 from pg_roles where rolname = 'anon') then
    revoke all on all tables in schema careercloud from anon;
    revoke all on all functions in schema careercloud from anon;
  end if;
end
$anon$;
"""


def _literal(value) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return repr(value)
    if isinstance(value, (dict, list)):
        import json

        if isinstance(value, list) and not value:
            return "'[]'::jsonb"
        return "'" + json.dumps(value, sort_keys=True).replace("'", "''") + "'::jsonb"
    return "'" + str(value).replace("'", "''") + "'"


def _choices_for(col: Col, version: str) -> Optional[tuple]:
    """The choices a column had as of ``version`` (a widened column keeps its original
    list in the migration that created it)."""
    if col.widened and version < col.widened[0]:
        return col.widened[1]
    return col.choices


def _column_sql(name: str, col: Col, spec: EntitySpec) -> str:
    pg = PG_TYPES[col.kind]
    parts = [f"{name:<22} {pg}"]
    if name == "id":
        parts = [f"{'id':<22} text primary key check (id ~ '^{spec.prefix}_[0-9a-f]{{32}}$')"]
        return " ".join(parts)
    if name == "workspace_id":
        return f"{'workspace_id':<22} uuid not null references careercloud.workspaces (id) on delete cascade"
    if col.required:
        parts.append("not null")
    if col.default is not None:
        if col.kind == "tags":
            parts.append("default '{}'::text[]")
        else:
            parts.append(f"default {_literal(col.default)}")
    elif name in ("created_at", "updated_at"):
        parts.append("default now()")
    checks: List[str] = []
    if col.max_len is not None and col.kind == "text":
        checks.append(f"char_length({name}) <= {col.max_len}")
    choices = _choices_for(col, spec.migration)
    if choices:
        options = ", ".join(_literal(c) for c in choices)
        checks.append(f"{name} in ({options})")
    if col.minimum is not None:
        checks.append(f"{name} >= {col.minimum:g}")
    if col.maximum is not None:
        checks.append(f"{name} <= {col.maximum:g}")
    if checks:
        parts.append("check (" + " and ".join(checks) + ")")
    return " ".join(parts)


def _later(col: Col, spec: EntitySpec) -> bool:
    """True when a later migration adds this column to the table."""
    return bool(col.added) and col.added > spec.migration


def added_sql(version: str) -> str:
    """``alter table ... add column`` for columns ``version`` adds to existing tables."""
    out: List[str] = []
    for spec in ENTITIES.values():
        for name, col in spec.columns.items():
            if col.added != version or spec.migration >= version:
                continue
            if col.required and col.default is None:
                raise ValueError(f"{spec.name}.{name}: an added required column needs a default")
            out.append(f"alter table careercloud.{spec.table} add column {_column_sql(name, col, spec).strip()};")
            if col.index:
                out.append(f"create index {spec.table}_by_ws_{name} on careercloud.{spec.table} (workspace_id, {name});")
    return "\n".join(out) + ("\n" if out else "")


def table_sql(spec: EntitySpec) -> str:
    t = f"careercloud.{spec.table}"
    columns = {**COMMON_COLUMNS, **{n: c for n, c in spec.columns.items() if not _later(c, spec)}}
    lines = [f"create table {t} ("]
    body = [f"  {_column_sql(name, col, spec)}" for name, col in columns.items()]
    lines.append(",\n".join(body))
    lines.append(");")
    out = ["-- " + (spec.description or spec.name), "\n".join(lines), ""]

    out.append(f"create index {spec.table}_by_ws_created on {t} (workspace_id, created_at desc, id desc);")
    for name, col in spec.columns.items():
        if col.index and not _later(col, spec):
            out.append(f"create index {spec.table}_by_ws_{name} on {t} (workspace_id, {name});")
    for group in spec.unique:
        cols = ", ".join(group)
        nullable = [c for c in group if not spec.columns[c].required]
        where = ""
        if nullable:
            where = " where " + " and ".join(f"{c} is not null" for c in nullable)
        out.append(f"create unique index {spec.table}_uq_{'_'.join(group)} on {t} (workspace_id, {cols}){where};")

    out.append(f"create trigger {spec.table}_guard before update on {t}")
    out.append("  for each row execute function careercloud.guard_platform_row();")
    out.append(f"alter table {t} enable row level security;")
    admin = bool(spec.admin_only) and spec.admin_only <= spec.migration
    policies, grants = _policies(spec, admin=admin)
    out.extend(policies)
    out.append(f"grant {', '.join(grants)} on {t} to authenticated;")
    return "\n".join(out) + "\n"


def _policies(spec: EntitySpec, *, admin: bool) -> Tuple[List[str], List[str]]:
    """RLS policies and grants for a table: members read and writers write, or only
    workspace admins (owner/admin) for an ``admin_only`` table."""
    t = f"careercloud.{spec.table}"
    read = "careercloud.can_admin(workspace_id)" if admin else "careercloud.is_member(workspace_id)"
    write = "careercloud.can_admin(workspace_id)" if admin else "careercloud.can_write(workspace_id)"
    out = [f"create policy {spec.table}_select on {t} for select to authenticated", f"  using ({read});"]
    grants = ["select"]
    if not spec.system_write:
        out.append(f"create policy {spec.table}_insert on {t} for insert to authenticated")
        out.append(f"  with check ({write} and created_by = auth.uid());")
        grants.append("insert")
        if not spec.append_only:
            out.append(f"create policy {spec.table}_update on {t} for update to authenticated")
            out.append(f"  using ({write}) with check ({write});")
            out.append(f"create policy {spec.table}_delete on {t} for delete to authenticated")
            out.append(f"  using ({write});")
            grants += ["update", "delete"]
    return out, grants


def restrict_sql(version: str) -> str:
    """Replace the policies of tables an earlier migration created that ``version`` makes admin-only."""
    out: List[str] = []
    for spec in ENTITIES.values():
        if spec.admin_only != version or spec.migration >= version:
            continue
        t = f"careercloud.{spec.table}"
        ops = ["select"]
        if not spec.system_write:
            ops += ["insert"] if spec.append_only else ["insert", "update", "delete"]
        out.append(f"-- {spec.table}: workspace admins only")
        out.extend(f"drop policy {spec.table}_{op} on {t};" for op in ops)
        out.extend(_policies(spec, admin=True)[0])
    return "\n".join(out) + ("\n" if out else "")


def widen_sql(version: str) -> str:
    """``alter table`` statements for columns whose choices ``version`` widens. PostgreSQL
    names an inline column check ``<table>_<column>_check``."""
    out: List[str] = []
    for spec in ENTITIES.values():
        for name, col in spec.columns.items():
            if not col.widened or col.widened[0] != version:
                continue
            if col.max_len is not None or col.minimum is not None or col.maximum is not None:
                raise ValueError(f"{spec.name}.{name}: only a plain choices check can be widened")
            options = ", ".join(_literal(c) for c in col.choices)
            constraint = f"{spec.table}_{name}_check"
            out.append(f"-- {spec.table}.{name}: widened choices")
            out.append(f"alter table careercloud.{spec.table} drop constraint {constraint},")
            out.append(f"  add constraint {constraint} check ({name} in ({options}));")
    return "\n".join(out) + ("\n" if out else "")


def generate(version: str = "0003") -> str:
    parts = [{"0003": _HEADER, "0004": _HEADER_0004, "0005": _HEADER_0005, "0006": _HEADER_0006,
              "0007": _HEADER_0007, "0008": _HEADER_0008, "0009": _HEADER_0009}[version]]
    widen = widen_sql(version)
    if widen:
        parts.append("\n-- ---------------------------------------------------------------------------\n")
        parts.append(widen)
    added = added_sql(version)
    if added:
        parts.append("\n-- ---------------------------------------------------------------------------\n")
        parts.append(added)
    restrict = restrict_sql(version)
    if restrict:
        parts.append("\n-- ---------------------------------------------------------------------------\n")
        parts.append(restrict)
    for spec in ENTITIES.values():
        if spec.migration != version:
            continue
        parts.append("\n-- ---------------------------------------------------------------------------\n")
        parts.append(table_sql(spec))
    if version == "0007":
        parts.append(_EXTRA_0007)
    parts.append(_FOOTER)
    return "".join(parts)


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--write", action="store_true")
    args = parser.parse_args(argv)
    for version, path in GENERATED.items():
        sql = generate(version)
        if args.write:
            path.write_text(sql, encoding="utf-8", newline="\n")
            count = sum(1 for spec in ENTITIES.values() if spec.migration == version)
            print(f"wrote {path} ({len(sql)} bytes, {count} tables)")
        else:
            sys.stdout.write(sql)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
